export const SUBCATEGORIES_DATA = {
  FACE: [
    { id: 'face_1', name: 'Complete Face Collection' },
    { id: 'face_2', name: 'Concealer Palette' },
    { id: 'face_3', name: 'Blush' },
    { id: 'face_4', name: 'Highlighter' },
    { id: 'face_5', name: 'Foundation' },
    { id: 'face_6', name: 'Setting Spray' },
    { id: 'face_7', name: 'Makeup Remover' },
  ],
  EYES: [
    { id: 'eyes_1', name: 'Complete Eyes Collection' },
    { id: 'eyes_2', name: 'Eyeliner' },
    { id: 'eyes_3', name: 'Kajal' },
    { id: 'eyes_4', name: 'Mascara' },
    { id: 'eyes_5', name: 'Eye - Shadow' },
    { id: 'eyes_6', name: 'Eyebrow Enhancers' },
    { id: 'eyes_7', name: 'Eye Makeup Remover' },
  ],
  LIPS: [
    { id: 'lips_1', name: 'Complete Lips Collection' },
    { id: 'lips_2', name: 'Lipstick' },
    { id: 'lips_3', name: 'Lip Gloss' },
    { id: 'lips_4', name: 'Lip Tint' },
    { id: 'lips_5', name: 'Liquid Lipstick' },
    { id: 'lips_6', name: 'Lip Blur' },
    { id: 'lips_7', name: 'Lip Makeup Remover' },
  ],
  NAILS: [
    { id: 'nails_1', name: 'Complete Nails Collection' },
    { id: 'nails_2', name: 'Nail Polish' },
    { id: 'nails_3', name: 'Nail Polish Remover' },
    { id: 'nails_4', name: 'Nail Polish Sets' },
    { id: 'nails_5', name: 'Nail Art Kits' },
    { id: 'nails_6', name: 'Nail Tools' },
    { id: 'nails_7', name: 'Nail Care' },
  ],
  'TOOLS & BRUSHES': [
    { id: 'tools_1', name: 'Complete Tools & Brushes Collection' },
    { id: 'tools_2', name: 'Silicon Applicators' },
    { id: 'tools_3', name: 'Eyelash Curlers' },
    { id: 'tools_4', name: 'Tweezers' },
    { id: 'tools_5', name: 'Sharpeners' },
    { id: 'tools_6', name: 'Mirrors' },
    { id: 'tools_7', name: 'Makeup Pouches' },
  ],
  PALETTES: [
    { id: 'palettes_1', name: 'Complete Palettes Collection' },
    { id: 'palettes_2', name: 'Eye Shadow Palettes' },
    { id: 'palettes_3', name: 'Concealer Palettes' },
    { id: 'palettes_4', name: 'Face Palettes' },
    { id: 'palettes_5', name: 'Blush Palettes' },
    { id: 'palettes_6', name: 'Lips Palettes' },
    { id: 'palettes_7', name: 'Highlighter Palettes' },
  ],
  FRAGRANCE: [
    { id: 'fragrance_1', name: 'Complete Fragrance Collection' },
    { id: 'fragrance_2', name: 'Perfume' },
    { id: 'fragrance_3', name: 'Attar' },
    { id: 'fragrance_4', name: 'For Him/For Her' },
    { id: 'fragrance_5', name: 'Combos & Sets' },
    { id: 'fragrance_6', name: 'LUXE Collection' },
    { id: 'fragrance_7', name: 'New Arrivals' },
  ],
  'KITS & COMBOS': [
    { id: 'kits_1', name: 'Complete Kits & Combos Collection' },
    { id: 'kits_2', name: 'Makeup Kits' },
    { id: 'kits_3', name: 'Makeup Combos' },
    { id: 'kits_4', name: 'LUXE Kits & Combos' },
  ],
  'GIFTS & ACCESSORIES': [
    { id: 'gifts_1', name: 'Complete Gifts Collection' },
    { id: 'gifts_2', name: 'PR Gifts' },
    { id: 'gifts_3', name: 'For Her' },
    { id: 'gifts_4', name: 'For Him' },
    { id: 'gifts_5', name: 'Handbags' },
    { id: 'gifts_6', name: 'Mirrors' },
    { id: 'gifts_7', name: 'Makeup Pouches' },
  ],
};
