import sunscreenImg from '../assets/images/sunscreen_spf50.webp';
import bodySunscreenImg from '../assets/images/body_sunscreen.webp';
import tintedSunscreenImg from '../assets/images/tinted_sunscreen.webp';
import gentleCleanserImg from '../assets/images/gentle_cleanser.webp';
import cleansingBalmImg from '../assets/images/cleansing_balm.webp';
import lipBalmImg from '../assets/images/lip_balm.webp';
import handCreamImg from '../assets/images/hand_cream.webp';
import pocketPerfumeImg from '../assets/images/pocket_perfume.webp';
import faceMistImg from '../assets/images/face_mist.webp';
import overnightMaskImg from '../assets/images/overnight_mask.webp';
import underEyePatchesImg from '../assets/images/under_eye_patches.webp';
import dailyMoisturiserImg from '../assets/images/daily_moisturiser.webp';
import settingSprayImg from '../assets/images/setting_spray.webp';
import niacinamideSerumImg from '../assets/images/niacinamide_serum.webp';
import giftGlowEssentialsImg from '../assets/images/gift_glow_essentials.webp';
import giftHydrationImg from '../assets/images/gift_hydration.webp';
import giftSunProtectionImg from '../assets/images/gift_sun_protection.webp';
import giftEverydayImg from '../assets/images/gift_everyday.webp';
import giftLuxuryImg from '../assets/images/gift_luxury.webp';
import giftTravelImg from '../assets/images/gift_travel.webp';
import giftGlowRepairImg from '../assets/images/gift_glow_repair.webp';
import giftPremiumImg from '../assets/images/gift_premium.webp';

// Generic gallery images for demo purposes (Side, Back, Lifestyle)
// In a real app, these would be specific to each product.
const getGallery = (mainImg) => [
  mainImg, 
  mainImg.replace('.webp', '_side.webp'),
  mainImg.replace('.webp', '_back.webp'),
  mainImg.replace('.webp', '_lifestyle.webp')
];

export const skincareProducts = [
  { 
    id: 101, 
    name: "COSKINn Sunscreen SPF 50", 
    originalPrice: 899,
    price: 789, 
    discountBadge: "12% OFF",
    rating: 4.8, 
    reviews: 356,
    category: "Skincare", 
    image: sunscreenImg, 
    images: getGallery(sunscreenImg),
    badge: "BEST SELLER",
    shortDescription: "Broad-spectrum SPF 50 protection with a lightweight, non-greasy finish.",
    longDescription: "Our flagship sunscreen provides ultimate UVA and UVB protection while keeping your skin hydrated and glowing. The lightweight formula absorbs instantly without leaving a white cast, making it perfect for daily use under makeup.",
    benefits: ["Broad-spectrum protection", "No white cast", "Hydrating formula", "Non-comedogenic"],
    keyIngredients: ["Zinc Oxide", "Niacinamide", "Hyaluronic Acid"],
    howToUse: "Apply generously to face and neck 15 minutes before sun exposure. Reapply every 2 hours.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Sun Protection, Anti-aging",
    texture: "Lightweight Lotion",
    fragrance: "Fragrance-Free",
    netQuantity: "50ml",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 124
  },
  { 
    id: 102, 
    name: "COSKINn Body Sunscreen SPF 50", 
    originalPrice: 1299,
    price: 1099, 
    discountBadge: "15% OFF",
    rating: 4.7, 
    reviews: 218,
    category: "Skincare", 
    image: bodySunscreenImg, 
    images: getGallery(bodySunscreenImg),
    badge: "NEW",
    shortDescription: "Full-body sun protection that nourishes and shields your skin.",
    longDescription: "A luxurious body sunscreen designed to protect and deeply moisturize your skin. Its fast-absorbing formula ensures you stay protected from harmful rays while enjoying a silky-smooth finish.",
    benefits: ["Water-resistant", "Deeply moisturizing", "Fast-absorbing", "Non-sticky"],
    keyIngredients: ["Titanium Dioxide", "Shea Butter", "Vitamin E"],
    howToUse: "Apply generously all over the body. Massage until fully absorbed.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Sun Protection, Dryness",
    texture: "Cream",
    fragrance: "Subtle Coconut",
    netQuantity: "150ml",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 85
  },
  { 
    id: 103, 
    name: "COSKINn Tinted Sunscreen SPF 50", 
    originalPrice: 999,
    price: 899, 
    discountBadge: "10% OFF",
    rating: 4.9, 
    reviews: 412,
    category: "Skincare", 
    image: tintedSunscreenImg, 
    images: getGallery(tintedSunscreenImg),
    badge: "TRENDING",
    shortDescription: "Sun protection meets sheer, glowing coverage.",
    longDescription: "Combine your daily sun protection with a flawless, sheer tint. This tinted sunscreen evens out skin tone while providing robust SPF 50 defense, leaving a radiant, dewy finish.",
    benefits: ["Evens skin tone", "Radiant finish", "High sun protection", "Blurs imperfections"],
    keyIngredients: ["Iron Oxides", "Zinc Oxide", "Squalane"],
    howToUse: "Apply evenly to the face as the last step of your skincare routine.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Uneven Skin Tone, Sun Protection",
    texture: "Tinted Fluid",
    fragrance: "Fragrance-Free",
    netQuantity: "50ml",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 210
  },
  { 
    id: 104, 
    name: "COSKINn Gentle Cleanser", 
    originalPrice: 599,
    price: 499, 
    discountBadge: "16% OFF",
    rating: 4.8, 
    reviews: 589,
    category: "Skincare", 
    image: gentleCleanserImg, 
    images: getGallery(gentleCleanserImg),
    badge: "MUST HAVE",
    shortDescription: "A hydrating, non-stripping cleanser for daily purification.",
    longDescription: "Gently remove dirt, oil, and makeup without disrupting your skin's natural barrier. Formulated with soothing botanical extracts, this cleanser leaves skin feeling fresh, soft, and balanced.",
    benefits: ["Non-stripping", "Removes makeup", "Soothes skin", "pH balanced"],
    keyIngredients: ["Ceramides", "Aloe Vera", "Chamomile Extract"],
    howToUse: "Massage a small amount onto damp skin in circular motions. Rinse thoroughly.",
    suitableSkinType: "Sensitive & Dry Skin",
    skinConcerns: "Dryness, Redness",
    texture: "Gel-to-Foam",
    fragrance: "Mild Floral",
    netQuantity: "100ml",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 340
  },
  { 
    id: 105, 
    name: "COSKINn Cleansing Balm", 
    originalPrice: 899,
    price: 719, 
    discountBadge: "20% OFF",
    rating: 4.9, 
    reviews: 1024,
    category: "Skincare", 
    image: cleansingBalmImg, 
    images: getGallery(cleansingBalmImg),
    badge: "VIRAL",
    shortDescription: "Melt away stubborn makeup effortlessly with this luxurious balm.",
    longDescription: "Experience the ultimate first cleanse. This buttery cleansing balm transforms into a silky oil upon application, melting away waterproof makeup, sunscreen, and impurities while nourishing the skin.",
    benefits: ["Melts waterproof makeup", "Nourishing", "Leaves zero residue", "Softens skin"],
    keyIngredients: ["Papaya Extract", "Sunflower Seed Oil", "Vitamin E"],
    howToUse: "Scoop a generous amount and massage onto dry skin. Add water to emulsify, then rinse.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Makeup Removal, Clogged Pores",
    texture: "Solid Balm to Oil",
    fragrance: "Subtle Citrus",
    netQuantity: "80g",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 150
  },
  { 
    id: 1051, 
    name: "COSKINn Cleansing Balm Mini", 
    originalPrice: 399,
    price: 299, 
    discountBadge: "25% OFF",
    rating: 4.8, 
    reviews: 312,
    category: "Skincare", 
    image: cleansingBalmImg, 
    images: getGallery(cleansingBalmImg),
    badge: "TRAVEL SIZE",
    shortDescription: "Perfect travel companion to melt away makeup on-the-go.",
    longDescription: "All the power of our signature cleansing balm in a travel-friendly mini size. Melting texture that leaves skin perfectly prepped for secondary cleansing.",
    benefits: ["Travel-friendly", "Nourishing", "Melts waterproof mascara", "Non-stripping"],
    keyIngredients: ["Papaya Extract", "Sunflower Seed Oil", "Vitamin E"],
    howToUse: "Scoop a hazelnut-sized amount and massage onto dry skin. Rinse with warm water.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Makeup Removal, Impurities",
    texture: "Solid Balm to Oil",
    fragrance: "Subtle Citrus",
    netQuantity: "25g",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 120
  },
  { 
    id: 1052, 
    name: "COSKINn Cleansing Balm Jumbo Pack", 
    originalPrice: 1499,
    price: 1199, 
    discountBadge: "20% OFF",
    rating: 4.9, 
    reviews: 567,
    category: "Skincare", 
    image: cleansingBalmImg, 
    images: getGallery(cleansingBalmImg),
    badge: "BEST VALUE",
    shortDescription: "Our signature makeup-melting balm in a jumbo eco-friendly size.",
    longDescription: "Get more of what you love. Our double-sized jumbo pack ensures you never run out of your favorite first cleanse, while reducing packaging waste by 30%.",
    benefits: ["Value size", "Eco-friendly packaging", "Deep cleansing", "Skin hydrating"],
    keyIngredients: ["Papaya Extract", "Sunflower Seed Oil", "Vitamin E"],
    howToUse: "Scoop a generous amount and massage onto dry skin. Emulsify and rinse off.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Makeup Removal, Clogged Pores",
    texture: "Solid Balm to Oil",
    fragrance: "Subtle Citrus",
    netQuantity: "150g",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 80
  },
  { 
    id: 1053, 
    name: "COSKINn Rose Infused Cleansing Balm", 
    originalPrice: 999,
    price: 799, 
    discountBadge: "20% OFF",
    rating: 4.8, 
    reviews: 145,
    category: "Skincare", 
    image: cleansingBalmImg, 
    images: getGallery(cleansingBalmImg),
    badge: "NEW LAUNCH",
    shortDescription: "Infused with pure rose damascena wax for a soothing floral cleanse.",
    longDescription: "A luxurious floral variant of our bestselling balm. Nourishes dry and sensitive skin while calming irritation and melting away stubborn foundation and mascara.",
    benefits: ["Soothing floral scent", "Calms redness", "Extra nourishing", "Non-irritating"],
    keyIngredients: ["Rose Damascena Wax", "Rosehip Oil", "Sweet Almond Oil"],
    howToUse: "Warm between palms and massage gently onto dry face. Emulsify and wipe clean.",
    suitableSkinType: "Dry & Sensitive Skin",
    skinConcerns: "Redness, Dryness, Makeup Removal",
    texture: "Buttery Rose Balm",
    fragrance: "Natural Damask Rose",
    netQuantity: "80g",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 65
  },
  { 
    id: 1054, 
    name: "COSKINn Charcoal Pore Cleansing Balm", 
    originalPrice: 949,
    price: 749, 
    discountBadge: "21% OFF",
    rating: 4.7, 
    reviews: 98,
    category: "Skincare", 
    image: cleansingBalmImg, 
    images: getGallery(cleansingBalmImg),
    badge: "PORE CLEARING",
    shortDescription: "Activated charcoal draws out impurities and excess sebum.",
    longDescription: "Perfect for oily and acne-prone skin. Infused with black activated charcoal to clarify pores, prevent blackheads, and dissolve oily sebum alongside makeup.",
    benefits: ["Detoxifies skin", "Reduces blackheads", "Balances oil production", "Deep pore clean"],
    keyIngredients: ["Activated Bamboo Charcoal", "Salicylic Acid", "Tea Tree Oil"],
    howToUse: "Massage over face, paying extra attention to T-zone. Emulsify and rinse thoroughly.",
    suitableSkinType: "Oily & Acne-Prone Skin",
    skinConcerns: "Excess Sebum, Blackheads, Pores",
    texture: "Clarifying Black Balm",
    fragrance: "Eucalyptus & Tea Tree",
    netQuantity: "80g",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 45
  },
  { 
    id: 1055, 
    name: "COSKINn Matcha Soothing Cleansing Balm", 
    originalPrice: 969,
    price: 769, 
    discountBadge: "20% OFF",
    rating: 4.8, 
    reviews: 112,
    category: "Skincare", 
    image: cleansingBalmImg, 
    images: getGallery(cleansingBalmImg),
    badge: "CALMING",
    shortDescription: "Antioxidant-rich organic matcha green tea calms stressed skin.",
    longDescription: "Enriched with ceremonial grade matcha green tea extract to neutralize environmental pollutants while lifting away face and eye makeup without stripping skin moisture.",
    benefits: ["Antioxidant-rich", "Neutralizes pollutants", "Calms skin irritation", "Non-drying"],
    keyIngredients: ["Organic Matcha Powder", "Green Tea Seed Oil", "Centella Asiatica"],
    howToUse: "Apply to dry face, massage, add warm water to turn into milk, and rinse off.",
    suitableSkinType: "Sensitive & Combination Skin",
    skinConcerns: "Irritation, Pollution Defense",
    texture: "Green Creamy Balm",
    fragrance: "Calming Green Tea",
    netQuantity: "80g",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 50
  },
  { 
    id: 1056, 
    name: "COSKINn Cleansing Balm Double Duo", 
    originalPrice: 1798,
    price: 1299, 
    discountBadge: "27% OFF",
    rating: 4.9, 
    reviews: 489,
    category: "Skincare", 
    image: cleansingBalmImg, 
    images: getGallery(cleansingBalmImg),
    badge: "COMBO DEAL",
    shortDescription: "Double the glow. A set of two full-sized cleansing balms.",
    longDescription: "Keep one on your vanity and one in your travel kit. Contains two full-sized jars of our bestselling makeup-melting balm to guarantee continuous clear skin.",
    benefits: ["Bundle savings", "Stock up value", "Perfect first cleanse duo", "Deeply nourishing"],
    keyIngredients: ["Papaya Extract", "Sunflower Seed Oil", "Vitamin E"],
    howToUse: "Use a scoop daily as the first step of your double cleansing routine.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Makeup Removal, Impurities",
    texture: "Solid Balm to Oil",
    fragrance: "Subtle Citrus",
    netQuantity: "2 x 80g",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 110
  },
  { 
    id: 1057, 
    name: "COSKINn Cleansing Balm & Mist Set", 
    originalPrice: 1398,
    price: 1049, 
    discountBadge: "25% OFF",
    rating: 4.9, 
    reviews: 224,
    category: "Skincare", 
    image: cleansingBalmImg, 
    images: getGallery(cleansingBalmImg),
    badge: "BEST SELLER",
    shortDescription: "A complete skin prep duo: Cleansing Balm and Face Mist.",
    longDescription: "Melt away makeup with our nourishing Cleansing Balm, then follow up with our Strawberry Glow Face Mist to lock in hydration and antioxidants.",
    benefits: ["Complete prep routine", "Hydrates & refreshes", "Melts makeup easily", "Dermatologist choice"],
    keyIngredients: ["Papaya Extract", "Strawberry Extract", "Vitamin E", "Hyaluronic Acid"],
    howToUse: "First cleanse with balm, rinse, then mist face generously to lock in moisture.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Makeup Removal, Dehydration",
    texture: "Balm + Mist Set",
    fragrance: "Citrus & Strawberry",
    netQuantity: "80g + 100ml",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 75
  },
  { 
    id: 106, 
    name: "COSKINn Lip Balm SPF", 
    originalPrice: 349,
    price: 299, 
    discountBadge: "14% OFF",
    rating: 4.7, 
    reviews: 420,
    category: "Skincare", 
    image: lipBalmImg, 
    images: getGallery(lipBalmImg),
    badge: "DAILY ESSENTIAL",
    shortDescription: "Hydrating lip care with essential sun protection.",
    longDescription: "Protect your delicate lips from sun damage while keeping them soft and plump. This SPF-infused lip balm delivers intense hydration and a subtle sheen.",
    benefits: ["Sun protection", "Intense hydration", "Heals chapped lips", "Subtle sheen"],
    keyIngredients: ["Shea Butter", "Beeswax", "SPF Filters"],
    howToUse: "Apply generously to lips as needed, especially before sun exposure.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Dry/Chapped Lips, Sun Protection",
    texture: "Smooth Stick",
    fragrance: "Strawberry",
    netQuantity: "4g",
    shelfLife: "18 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 500
  },
  { 
    id: 107, 
    name: "COSKINn Nourishing Hand Cream", 
    originalPrice: 499,
    price: 439, 
    discountBadge: "12% OFF",
    rating: 4.8, 
    reviews: 185,
    category: "Skincare", 
    image: handCreamImg, 
    images: getGallery(handCreamImg),
    badge: "NEW",
    shortDescription: "Silky, fast-absorbing hydration for dry hands.",
    longDescription: "Revive dry, overworked hands with our intensely nourishing hand cream. Its non-greasy formula absorbs quickly, leaving hands feeling velvety soft and beautifully scented.",
    benefits: ["Intense hydration", "Non-greasy", "Softens cuticles", "Long-lasting moisture"],
    keyIngredients: ["Shea Butter", "Almond Oil", "Glycerin"],
    howToUse: "Massage into hands and cuticles whenever they feel dry.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Dryness, Rough Texture",
    texture: "Rich Cream",
    fragrance: "Rose & Vanilla",
    netQuantity: "50g",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 220
  },
  { 
    id: 108, 
    name: "COSKINn Pocket Perfume", 
    originalPrice: 399,
    price: 349, 
    discountBadge: "12% OFF",
    rating: 4.6, 
    reviews: 310,
    category: "Skincare", 
    image: pocketPerfumeImg, 
    images: getGallery(pocketPerfumeImg),
    badge: "ON-THE-GO",
    shortDescription: "A luxurious, long-lasting fragrance in a travel-friendly size.",
    longDescription: "Carry luxury wherever you go. Our pocket perfume features a highly concentrated blend of floral and musky notes, designed to keep you feeling fresh and elegant all day.",
    benefits: ["Travel-friendly", "Long-lasting", "Premium scent", "Elegant packaging"],
    keyIngredients: ["Essential Oils", "Perfume Base"],
    howToUse: "Spray on pulse points (wrists, neck, behind ears) as desired.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Body Odor, Fragrance",
    texture: "Liquid Spray",
    fragrance: "Floral Musk",
    netQuantity: "20ml",
    shelfLife: "36 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 180
  },
  { 
    id: 109, 
    name: "COSKINn Face Mist", 
    originalPrice: 599,
    price: 499, 
    discountBadge: "16% OFF",
    rating: 4.8, 
    reviews: 275,
    category: "Skincare", 
    image: faceMistImg, 
    images: getGallery(faceMistImg),
    badge: "REFRESHING",
    shortDescription: "An instant boost of hydration and glow.",
    longDescription: "Revitalize tired skin with a single spritz. Infused with rose water and hyaluronic acid, this face mist instantly hydrates, soothes, and sets makeup for a dewy finish.",
    benefits: ["Instant hydration", "Sets makeup", "Soothes skin", "Dewy finish"],
    keyIngredients: ["Rose Water", "Hyaluronic Acid", "Green Tea Extract"],
    howToUse: "Hold 8-10 inches away from face and spray evenly. Use throughout the day to refresh.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Dehydration, Dullness",
    texture: "Fine Mist",
    fragrance: "Fresh Rose",
    netQuantity: "100ml",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 290
  },
  { 
    id: 110, 
    name: "COSKINn Overnight Mask", 
    originalPrice: 1299,
    price: 1099, 
    discountBadge: "15% OFF",
    rating: 4.9, 
    reviews: 512,
    category: "Skincare", 
    image: overnightMaskImg, 
    images: getGallery(overnightMaskImg),
    badge: "AWARD WINNER",
    shortDescription: "Wake up to plumper, more radiant skin.",
    longDescription: "Work with your skin's natural nightly repair process. This luxurious overnight mask intensely hydrates, repairs the moisture barrier, and visibly brightens your complexion by morning.",
    benefits: ["Deep repair", "Intense hydration", "Brightens skin", "Plumping effect"],
    keyIngredients: ["Peptides", "Ceramides", "Vitamin C"],
    howToUse: "Apply a generous layer as the final step of your evening routine. Leave on overnight.",
    suitableSkinType: "Dry & Combination Skin",
    skinConcerns: "Dullness, Fine Lines, Dryness",
    texture: "Gel-Cream",
    fragrance: "Lavender Dream",
    netQuantity: "50g",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 115
  },
  { 
    id: 111, 
    name: "COSKINn Under Eye Patches", 
    originalPrice: 799,
    price: 679, 
    discountBadge: "15% OFF",
    rating: 4.7, 
    reviews: 388,
    category: "Skincare", 
    image: underEyePatchesImg, 
    images: getGallery(underEyePatchesImg),
    badge: "LUXURY",
    shortDescription: "Instant depuffing and brightening for tired eyes.",
    longDescription: "Revitalize your under-eye area in 15 minutes. These cooling hydrogel patches are infused with caffeine and collagen to visibly reduce dark circles, puffiness, and fine lines.",
    benefits: ["Depuffs", "Reduces dark circles", "Smooths fine lines", "Cooling effect"],
    keyIngredients: ["Caffeine", "Collagen", "Gold Extract"],
    howToUse: "Apply onto clean, dry under-eye area. Leave on for 15-20 minutes, then discard.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Dark Circles, Puffiness",
    texture: "Hydrogel",
    fragrance: "Fragrance-Free",
    netQuantity: "30 Pairs",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 160
  },
  { 
    id: 112, 
    name: "COSKINn Daily Moisturiser", 
    originalPrice: 899,
    price: 799, 
    discountBadge: "11% OFF",
    rating: 4.8, 
    reviews: 640,
    category: "Skincare", 
    image: dailyMoisturiserImg, 
    images: getGallery(dailyMoisturiserImg),
    badge: "ESSENTIAL",
    shortDescription: "24-hour hydration with a lightweight feel.",
    longDescription: "Lock in moisture all day long with our daily moisturiser. The perfectly balanced formula absorbs quickly, leaving skin supple, smooth, and prepped for makeup.",
    benefits: ["24-hour hydration", "Lightweight", "Improves skin texture", "Non-greasy"],
    keyIngredients: ["Hyaluronic Acid", "Squalane", "Vitamin E"],
    howToUse: "Apply morning and night to cleansed face and neck.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Dryness, Uneven Texture",
    texture: "Lightweight Cream",
    fragrance: "Mild Fresh",
    netQuantity: "50ml",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 450
  },
  { 
    id: 113, 
    name: "COSKINn Hydrating Setting Spray", 
    originalPrice: 699,
    price: 579, 
    discountBadge: "17% OFF",
    rating: 4.7, 
    reviews: 215,
    category: "Skincare", 
    image: settingSprayImg, 
    images: getGallery(settingSprayImg),
    badge: "NEW",
    shortDescription: "Lock in your look with a burst of hydration.",
    longDescription: "A micro-fine setting spray that fuses makeup and skincare. It sets makeup for up to 16 hours while delivering a continuous boost of hydration, ensuring a radiant, non-cakey finish.",
    benefits: ["16-hour wear", "Hydrating", "Micro-fine mist", "Radiant finish"],
    keyIngredients: ["Aloe Vera", "Green Tea Extract", "Glycerin"],
    howToUse: "Shake well. Hold 8-10 inches away and spray in an 'X' and 'T' motion.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Makeup Longevity, Dryness",
    texture: "Fine Liquid Mist",
    fragrance: "Fresh Aloe",
    netQuantity: "100ml",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 280
  },
  { 
    id: 114, 
    name: "COSKINn Niacinamide Serum", 
    originalPrice: 1099,
    price: 879, 
    discountBadge: "20% OFF",
    rating: 4.9, 
    reviews: 890,
    category: "Skincare", 
    image: niacinamideSerumImg, 
    images: getGallery(niacinamideSerumImg),
    badge: "HOLY GRAIL",
    shortDescription: "Potent 10% Niacinamide to refine pores and tone.",
    longDescription: "Transform your skin texture with our potent Niacinamide serum. Formulated to minimize the appearance of enlarged pores, control excess sebum, and fade dark spots for a clear, luminous complexion.",
    benefits: ["Minimizes pores", "Controls oil", "Fades dark spots", "Improves skin tone"],
    keyIngredients: ["10% Niacinamide", "Zinc PCA", "Hyaluronic Acid"],
    howToUse: "Apply 2-3 drops to clean skin before heavier creams, morning and night.",
    suitableSkinType: "Oily, Combination, & Acne-Prone Skin",
    skinConcerns: "Enlarged Pores, Blemishes, Oiliness",
    texture: "Lightweight Serum",
    fragrance: "Fragrance-Free",
    netQuantity: "30ml",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 195
  },
  { 
    id: 201, 
    name: "COSKINn Glow Essentials Gift Set", 
    originalPrice: 2597,
    price: 1999, 
    discountBadge: "23% OFF",
    rating: 4.9, 
    reviews: 512,
    category: "Gift Sets", 
    image: giftGlowEssentialsImg, 
    images: getGallery(giftGlowEssentialsImg),
    badge: "PERFECT GIFT",
    shortDescription: "A curated trio featuring Niacinamide Serum, Gentle Cleanser, and Daily Moisturiser.",
    longDescription: "Give the gift of radiant skin. This beautifully packaged Glow Essentials Gift Set includes everything needed for a complete, brightening daily routine. Housed in a premium COSKINn luxury box with a beautiful ribbon finish.",
    benefits: ["Complete daily routine", "Brightens complexion", "Luxury gift packaging", "Exceptional value"],
    keyIngredients: ["Niacinamide", "Ceramides", "Hyaluronic Acid"],
    howToUse: "Step 1: Cleanse. Step 2: Apply Serum. Step 3: Lock in with Moisturiser.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Dullness, Uneven Texture",
    texture: "Various",
    fragrance: "Signature Fresh",
    netQuantity: "3 Items",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 150
  },
  { 
    id: 202, 
    name: "COSKINn Hydration Ritual Gift Set", 
    originalPrice: 2597,
    price: 1899, 
    discountBadge: "26% OFF",
    rating: 4.8, 
    reviews: 320,
    category: "Gift Sets", 
    image: giftHydrationImg, 
    images: getGallery(giftHydrationImg),
    badge: "BEST SELLER",
    shortDescription: "The ultimate hydration boost featuring Face Mist, Moisturiser, and Overnight Mask.",
    longDescription: "Quench thirsty skin with this ultimate hydration bundle. Packed inside a premium gift box, this set ensures 72-hour moisture and a dewy, glowing complexion for any special occasion.",
    benefits: ["72-hour hydration", "Repairs skin barrier", "Premium presentation box", "Plumps skin"],
    keyIngredients: ["Hyaluronic Acid", "Rose Water", "Peptides"],
    howToUse: "Mist throughout the day, moisturise morning and night, and use the mask overnight.",
    suitableSkinType: "Dry & Combination Skin",
    skinConcerns: "Dehydration, Dullness",
    texture: "Various",
    fragrance: "Rose & Lavender",
    netQuantity: "3 Items",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 85
  },
  { 
    id: 203, 
    name: "COSKINn Sun Protection Kit", 
    originalPrice: 2547,
    price: 1799, 
    discountBadge: "29% OFF",
    rating: 4.7, 
    reviews: 410,
    category: "Gift Sets", 
    image: giftSunProtectionImg, 
    images: getGallery(giftSunProtectionImg),
    badge: "TRAVEL ESSENTIAL",
    shortDescription: "Complete SPF defense with Face Sunscreen, Body Sunscreen, and SPF Lip Balm.",
    longDescription: "The perfect getaway gift. This beautifully wrapped kit provides comprehensive broad-spectrum SPF 50 protection from head to toe. Keep their skin safe, hydrated, and protected.",
    benefits: ["Full body protection", "No white cast", "Travel ready", "Premium gift packaging"],
    keyIngredients: ["Zinc Oxide", "Titanium Dioxide", "Shea Butter"],
    howToUse: "Apply generously to face, body, and lips 15 minutes before sun exposure.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Sun Protection, Anti-aging",
    texture: "Lotions & Balm",
    fragrance: "Subtle Coconut",
    netQuantity: "3 Items",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 200
  },
  { 
    id: 204, 
    name: "COSKINn Everyday Essentials Kit", 
    originalPrice: 1997,
    price: 1499, 
    discountBadge: "25% OFF",
    rating: 4.8, 
    reviews: 625,
    category: "Gift Sets", 
    image: giftEverydayImg, 
    images: getGallery(giftEverydayImg),
    badge: "PERFECT GIFT",
    shortDescription: "The daily must-haves: Gentle Cleanser, Moisturiser, and Hand Cream.",
    longDescription: "A universally loved gift. This kit features our most popular daily essentials designed to keep skin clean, soft, and deeply moisturised. Elegantly boxed for any celebration.",
    benefits: ["Gentle care", "Deeply moisturizing", "Great for beginners", "Luxury packaging"],
    keyIngredients: ["Ceramides", "Aloe Vera", "Almond Oil"],
    howToUse: "Cleanse face daily, apply moisturiser, and use hand cream as needed.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Dryness, Maintenance",
    texture: "Various",
    fragrance: "Mild Floral",
    netQuantity: "3 Items",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 310
  },
  { 
    id: 205, 
    name: "COSKINn Luxury Self-Care Box", 
    originalPrice: 3596,
    price: 2699, 
    discountBadge: "25% OFF",
    rating: 4.9, 
    reviews: 185,
    category: "Gift Sets", 
    image: giftLuxuryImg, 
    images: getGallery(giftLuxuryImg),
    badge: "LIMITED EDITION",
    shortDescription: "The ultimate indulgence: Cleansing Balm, Face Mist, Eye Patches, and Overnight Mask.",
    longDescription: "Treat someone special to the ultimate spa-at-home experience. This deluxe box includes our viral cleansing balm, refreshing face mist, luxurious gold eye patches, and repair mask.",
    benefits: ["Spa-at-home", "Deep repair", "Luxury unboxing experience", "Premium ingredients"],
    keyIngredients: ["Gold Extract", "Papaya Extract", "Peptides"],
    howToUse: "Melt makeup with balm, mist face, apply eye patches, and finish with overnight mask.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Stress, Fatigue, Dullness",
    texture: "Various",
    fragrance: "Calming Spa",
    netQuantity: "4 Items",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 50
  },
  { 
    id: 206, 
    name: "COSKINn Travel Skincare Kit", 
    originalPrice: 1899,
    price: 1399, 
    discountBadge: "26% OFF",
    rating: 4.7, 
    reviews: 440,
    category: "Gift Sets", 
    image: giftTravelImg, 
    images: getGallery(giftTravelImg),
    badge: "TRAVEL READY",
    shortDescription: "Mini Cleanser, Mini Moisturiser, Mini Sunscreen, and full-size Lip Balm.",
    longDescription: "Never compromise on skincare while traveling. This TSA-friendly kit comes in a beautiful bespoke travel pouch inside a premium gift box, containing all the essentials for glowing skin on the go.",
    benefits: ["TSA-friendly sizes", "Complete routine", "Includes travel pouch", "Perfect for vacations"],
    keyIngredients: ["Niacinamide", "Ceramides", "Hyaluronic Acid"],
    howToUse: "Use as a complete 3-step routine while traveling.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Travel, Maintenance",
    texture: "Various",
    fragrance: "Signature Fresh",
    netQuantity: "4 Items",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 180
  },
  { 
    id: 207, 
    name: "COSKINn Glow & Repair Kit", 
    originalPrice: 2997,
    price: 2199, 
    discountBadge: "26% OFF",
    rating: 4.9, 
    reviews: 290,
    category: "Gift Sets", 
    image: giftGlowRepairImg, 
    images: getGallery(giftGlowRepairImg),
    badge: "AWARD WINNER",
    shortDescription: "Powerful repair trio: Niacinamide Serum, Overnight Mask, and Face Mist.",
    longDescription: "The ultimate overnight transformation kit. These three powerful products work synergistically to repair the skin barrier, minimize pores, and deliver intense glowing hydration by morning.",
    benefits: ["Intense repair", "Minimizes pores", "Overnight transformation", "Premium presentation"],
    keyIngredients: ["10% Niacinamide", "Peptides", "Rose Water"],
    howToUse: "Mist skin, apply serum, and lock in with the overnight mask before bed.",
    suitableSkinType: "Oily & Combination Skin",
    skinConcerns: "Pores, Uneven Texture, Barrier Repair",
    texture: "Various",
    fragrance: "Fresh Lavender",
    netQuantity: "3 Items",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 95
  },
  { 
    id: 208, 
    name: "COSKINn Premium Beauty Box", 
    originalPrice: 4795,
    price: 3499, 
    discountBadge: "27% OFF",
    rating: 5.0, 
    reviews: 112,
    category: "Gift Sets", 
    image: giftPremiumImg, 
    images: getGallery(giftPremiumImg),
    badge: "ULTIMATE LUXURY",
    shortDescription: "The complete collection: Cleanser, Serum, Moisturiser, Sunscreen, and Eye Patches.",
    longDescription: "Our most luxurious offering. The Premium Beauty Box contains five of our most celebrated, award-winning formulas housed in a stunning, heavyweight keepsake gift box. The ultimate gift for a true skincare aficionado.",
    benefits: ["Complete luxury routine", "Exceptional value", "Keepsake gift box", "Award-winning formulas"],
    keyIngredients: ["Gold Extract", "10% Niacinamide", "Hyaluronic Acid"],
    howToUse: "Follow the enclosed COSKINn routine guide for optimal results.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Comprehensive Care",
    texture: "Various",
    fragrance: "Signature Fresh",
    netQuantity: "5 Items",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 25
  },
  // --- NEW CLEANSERS WITH ADVANCED PDP DATA ---
  {
    id: 301,
    name: "COSKINn Hydrating Cleanser",
    originalPrice: 899,
    price: 699,
    discountBadge: "22% OFF",
    rating: 4.9,
    reviews: 1450,
    category: "Face Care",
    subcategory: "Cleanser",
    skinTypes: ["Dry Skin", "Normal Skin", "Sensitive Skin"],
    concerns: ["Dryness", "Dullness"],
    image: gentleCleanserImg,
    images: getGallery(gentleCleanserImg),
    badge: "HYDRATION BOOST",
    shortDescription: "A moisture-rich cleanser that melts away impurities without stripping your skin barrier.",
    longDescription: "Formulated with 3 essential ceramides and hyaluronic acid, this non-foaming hydrating cleanser effectively removes dirt and makeup while reinforcing your skin's natural protective barrier.",
    benefits: ["Deep Cleansing", "Hydration", "Maintains Skin Barrier", "Soap Free", "Paraben Free", "Cruelty Free"],
    keyIngredients: ["Ceramides", "Hyaluronic Acid", "Vitamin B5"],
    howToUse: [
      { step: "Step 1", title: "Wet Face", desc: "Splash face with lukewarm water." },
      { step: "Step 2", title: "Apply COSKINn Cleanser", desc: "Pump a coin-sized amount onto fingertips." },
      { step: "Step 3", title: "Massage for 30-60 Seconds", desc: "Gently massage in circular motions." },
      { step: "Step 4", title: "Rinse & Pat Dry", desc: "Rinse thoroughly and pat dry with a soft towel." }
    ],
    detailedIngredients: [
      { name: "Hyaluronic Acid", benefit: "Retains 1000x its weight in water for plump skin", skinType: "All Skin Types" },
      { name: "Ceramides", benefit: "Restores and maintains the skin's natural barrier", skinType: "Dry, Sensitive" },
      { name: "Vitamin B5", benefit: "Soothes and heals compromised skin", skinType: "Sensitive" }
    ],
    beforeAfter: { before: gentleCleanserImg, after: gentleCleanserImg }, // Reusing images for mock
    customerReviews: [
      { user: "Priya S.", rating: 5, date: "12 June 2026", text: "Completely cured my dry patches! Will never use another cleanser.", helpful: 124 },
      { user: "Aarti M.", rating: 4, date: "05 May 2026", text: "Very gentle, doesn't lather much but leaves skin soft.", helpful: 45 }
    ],
    faqs: [
      { q: "Suitable for Sensitive Skin?", a: "Yes, it is dermatologically tested and fragrance-free." },
      { q: "Can Teenagers Use It?", a: "Absolutely. It's gentle enough for daily teenage use." },
      { q: "Does It Remove Sunscreen?", a: "Yes, it effectively removes daily sunscreen and light makeup." }
    ],
    routine: [
      { step: "Cleanser", product: "COSKINn Hydrating Cleanser" },
      { step: "Toner", product: "COSKINn Face Mist" },
      { step: "Serum", product: "COSKINn Niacinamide Serum" },
      { step: "Moisturiser", product: "COSKINn Daily Moisturiser" },
      { step: "Sunscreen", product: "COSKINn Sunscreen SPF 50" }
    ],
    texture: "Creamy Lotion",
    netQuantity: "150 ml",
    shelfLife: "24 Months",
    countryOfOrigin: "India",
    manufacturedBy: "COSKINn Labs"
  },
  {
    id: 302,
    name: "COSKINn Foaming Cleanser",
    originalPrice: 799,
    price: 649,
    discountBadge: "18% OFF",
    rating: 4.8,
    reviews: 980,
    category: "Face Care",
    subcategory: "Cleanser",
    skinTypes: ["Oily Skin", "Combination Skin"],
    concerns: ["Oil Control", "Large Pores", "Acne"],
    image: gentleCleanserImg,
    images: getGallery(gentleCleanserImg),
    badge: "PORE CLEARING",
    shortDescription: "A refreshing foaming gel that deeply cleanses pores and controls excess oil.",
    longDescription: "This gel-to-foam cleanser deeply purifies without disrupting the skin barrier. Infused with Niacinamide to control sebum and tighten pores.",
    benefits: ["Deep Cleansing", "Oil Control", "Dermatologically Tested", "Paraben Free", "Sulphate Free", "Cruelty Free"],
    keyIngredients: ["Niacinamide", "Salicylic Acid", "Green Tea"],
    howToUse: [
      { step: "Step 1", title: "Wet Face", desc: "Splash face with lukewarm water." },
      { step: "Step 2", title: "Apply COSKINn Cleanser", desc: "Pump a coin-sized amount onto fingertips." },
      { step: "Step 3", title: "Massage for 30-60 Seconds", desc: "Gently massage in circular motions." },
      { step: "Step 4", title: "Rinse & Pat Dry", desc: "Rinse thoroughly and pat dry with a soft towel." }
    ],
    detailedIngredients: [
      { name: "Niacinamide", benefit: "Controls oil production and fades marks", skinType: "Oily, Combination" },
      { name: "Green Tea", benefit: "Antioxidant protection and soothing properties", skinType: "Acne Prone" }
    ],
    beforeAfter: { before: gentleCleanserImg, after: gentleCleanserImg },
    customerReviews: [
      { user: "Karan V.", rating: 5, date: "22 May 2026", text: "Best foaming wash for my oily T-zone.", helpful: 89 }
    ],
    faqs: [
      { q: "Can I Use It Daily?", a: "Yes, use twice a day for best results." },
      { q: "Fragrance Free?", a: "Yes, it contains no artificial fragrances." }
    ],
    routine: [
      { step: "Cleanser", product: "COSKINn Foaming Cleanser" },
      { step: "Toner", product: "COSKINn Face Mist" },
      { step: "Serum", product: "COSKINn Niacinamide Serum" },
      { step: "Moisturiser", product: "COSKINn Daily Moisturiser" },
      { step: "Sunscreen", product: "COSKINn Sunscreen SPF 50" }
    ],
    texture: "Gel to Foam",
    netQuantity: "150 ml",
    shelfLife: "24 Months",
    countryOfOrigin: "India",
    manufacturedBy: "COSKINn Labs"
  },
  {
    id: 303,
    name: "COSKINn Gel Cleanser",
    originalPrice: 849,
    price: 699,
    discountBadge: "17% OFF",
    rating: 4.7,
    reviews: 650,
    category: "Face Care",
    subcategory: "Cleanser",
    skinTypes: ["Normal Skin", "Combination Skin", "Sensitive Skin"],
    concerns: ["Blackheads", "Whiteheads"],
    image: gentleCleanserImg,
    images: getGallery(gentleCleanserImg),
    badge: "EVERYDAY GLOW",
    shortDescription: "A mild, pH-balanced gel cleanser for everyday freshness.",
    longDescription: "Formulated with Aloe Vera and Centella Asiatica, this soothing gel cleanser removes daily grime while keeping skin calm and balanced.",
    benefits: ["Hydration", "Maintains Skin Barrier", "Dermatologically Tested", "Cruelty Free"],
    keyIngredients: ["Aloe Vera", "Centella Asiatica"],
    howToUse: [
      { step: "Step 1", title: "Wet Face", desc: "Splash face with lukewarm water." },
      { step: "Step 2", title: "Apply COSKINn Cleanser", desc: "Pump a coin-sized amount onto fingertips." },
      { step: "Step 3", title: "Massage for 30-60 Seconds", desc: "Gently massage in circular motions." },
      { step: "Step 4", title: "Rinse & Pat Dry", desc: "Rinse thoroughly and pat dry with a soft towel." }
    ],
    detailedIngredients: [
      { name: "Aloe Vera", benefit: "Deeply hydrates and calms redness", skinType: "Sensitive" },
      { name: "Centella Asiatica", benefit: "Heals skin barrier", skinType: "All Skin Types" }
    ],
    beforeAfter: { before: gentleCleanserImg, after: gentleCleanserImg },
    customerReviews: [
      { user: "Neha R.", rating: 4, date: "10 Apr 2026", text: "Very refreshing, lovely texture.", helpful: 30 }
    ],
    faqs: [
      { q: "Does It Remove Makeup?", a: "It removes light makeup, but we recommend a double cleanse for heavy makeup." }
    ],
    routine: [
      { step: "Cleanser", product: "COSKINn Gel Cleanser" },
      { step: "Toner", product: "COSKINn Face Mist" },
      { step: "Serum", product: "COSKINn Niacinamide Serum" },
      { step: "Moisturiser", product: "COSKINn Daily Moisturiser" },
      { step: "Sunscreen", product: "COSKINn Sunscreen SPF 50" }
    ],
    texture: "Clear Gel",
    netQuantity: "150 ml",
    shelfLife: "24 Months",
    countryOfOrigin: "India",
    manufacturedBy: "COSKINn Labs"
  },
  {
    id: 304,
    name: "COSKINn Brightening Cleanser",
    originalPrice: 999,
    price: 849,
    discountBadge: "15% OFF",
    rating: 4.8,
    reviews: 880,
    category: "Face Care",
    subcategory: "Cleanser",
    skinTypes: ["Normal Skin", "Dry Skin", "Oily Skin", "Combination Skin"],
    concerns: ["Pigmentation", "Dullness"],
    image: gentleCleanserImg,
    images: getGallery(gentleCleanserImg),
    badge: "RADIANCE",
    shortDescription: "A Vitamin C infused cleanser to instantly brighten and even out skin tone.",
    longDescription: "Wash away dullness and reveal a luminous complexion with this antioxidant-rich cleanser. Vitamin C works to fade dark spots over time.",
    benefits: ["Brightening", "Deep Cleansing", "Sulphate Free", "Cruelty Free"],
    keyIngredients: ["Vitamin C", "Licorice Extract"],
    howToUse: [
      { step: "Step 1", title: "Wet Face", desc: "Splash face with lukewarm water." },
      { step: "Step 2", title: "Apply COSKINn Cleanser", desc: "Pump a coin-sized amount onto fingertips." },
      { step: "Step 3", title: "Massage for 30-60 Seconds", desc: "Gently massage in circular motions." },
      { step: "Step 4", title: "Rinse & Pat Dry", desc: "Rinse thoroughly and pat dry with a soft towel." }
    ],
    detailedIngredients: [
      { name: "Vitamin C", benefit: "Brightens and evens skin tone", skinType: "All Skin Types" },
      { name: "Licorice Extract", benefit: "Fades pigmentation", skinType: "Dull Skin" }
    ],
    beforeAfter: { before: gentleCleanserImg, after: gentleCleanserImg },
    customerReviews: [
      { user: "Rohan D.", rating: 5, date: "02 Mar 2026", text: "Gives an instant glow right after washing!", helpful: 156 }
    ],
    faqs: [
      { q: "Can I Use It Daily?", a: "Yes, it is gentle enough for daily AM and PM use." }
    ],
    routine: [
      { step: "Cleanser", product: "COSKINn Brightening Cleanser" },
      { step: "Toner", product: "COSKINn Face Mist" },
      { step: "Serum", product: "COSKINn Niacinamide Serum" },
      { step: "Moisturiser", product: "COSKINn Daily Moisturiser" },
      { step: "Sunscreen", product: "COSKINn Sunscreen SPF 50" }
    ],
    texture: "Creamy Gel",
    netQuantity: "150 ml",
    shelfLife: "24 Months",
    countryOfOrigin: "India",
    manufacturedBy: "COSKINn Labs"
  },
  {
    id: 305,
    name: "COSKINn Sensitive Cleanser",
    originalPrice: 899,
    price: 749,
    discountBadge: "16% OFF",
    rating: 4.9,
    reviews: 1200,
    category: "Face Care",
    subcategory: "Cleanser",
    skinTypes: ["Sensitive Skin", "Dry Skin"],
    concerns: ["Sensitive Skin", "Dryness"],
    image: gentleCleanserImg,
    images: getGallery(gentleCleanserImg),
    badge: "CALMING",
    shortDescription: "An ultra-gentle, fragrance-free formula for the most reactive skin types.",
    longDescription: "Formulated without essential oils or harsh surfactants, this cleanser purifies without triggering redness or irritation.",
    benefits: ["Maintains Skin Barrier", "Dermatologically Tested", "Soap Free", "Paraben Free", "Sulphate Free", "Cruelty Free"],
    keyIngredients: ["Colloidal Oatmeal", "Ceramides"],
    howToUse: [
      { step: "Step 1", title: "Wet Face", desc: "Splash face with lukewarm water." },
      { step: "Step 2", title: "Apply COSKINn Cleanser", desc: "Pump a coin-sized amount onto fingertips." },
      { step: "Step 3", title: "Massage for 30-60 Seconds", desc: "Gently massage in circular motions." },
      { step: "Step 4", title: "Rinse & Pat Dry", desc: "Rinse thoroughly and pat dry with a soft towel." }
    ],
    detailedIngredients: [
      { name: "Colloidal Oatmeal", benefit: "Clinically proven to soothe redness and itching", skinType: "Sensitive" },
      { name: "Ceramides", benefit: "Restores the skin barrier", skinType: "Sensitive" }
    ],
    beforeAfter: { before: gentleCleanserImg, after: gentleCleanserImg },
    customerReviews: [
      { user: "Shreya P.", rating: 5, date: "14 Feb 2026", text: "The only cleanser that doesn't make my skin burn.", helpful: 210 }
    ],
    faqs: [
      { q: "Suitable for Sensitive Skin?", a: "Yes, it is formulated specifically for hyper-sensitive skin." },
      { q: "Fragrance Free?", a: "100% fragrance and essential oil free." }
    ],
    routine: [
      { step: "Cleanser", product: "COSKINn Sensitive Cleanser" },
      { step: "Toner", product: "COSKINn Face Mist" },
      { step: "Serum", product: "COSKINn Niacinamide Serum" },
      { step: "Moisturiser", product: "COSKINn Daily Moisturiser" },
      { step: "Sunscreen", product: "COSKINn Sunscreen SPF 50" }
    ],
    texture: "Milky Lotion",
    netQuantity: "150 ml",
    shelfLife: "24 Months",
    countryOfOrigin: "India",
    manufacturedBy: "COSKINn Labs"
  },
  {
    id: 306,
    name: "COSKINn Acne Control Cleanser",
    originalPrice: 949,
    price: 799,
    discountBadge: "15% OFF",
    rating: 4.7,
    reviews: 1800,
    category: "Face Care",
    subcategory: "Cleanser",
    skinTypes: ["Oily Skin", "Acne Prone"],
    concerns: ["Acne", "Large Pores", "Blackheads"],
    image: gentleCleanserImg,
    images: getGallery(gentleCleanserImg),
    badge: "BHA POWER",
    shortDescription: "A 2% Salicylic Acid cleanser to fight breakouts and unclog pores.",
    longDescription: "Target active acne and prevent future breakouts with this BHA-infused cleanser. It gently exfoliates dead skin cells while deep-cleaning pores.",
    benefits: ["Oil Control", "Deep Cleansing", "Dermatologically Tested", "Paraben Free", "Cruelty Free"],
    keyIngredients: ["Salicylic Acid", "Tea Tree Extract"],
    howToUse: [
      { step: "Step 1", title: "Wet Face", desc: "Splash face with lukewarm water." },
      { step: "Step 2", title: "Apply COSKINn Cleanser", desc: "Pump a coin-sized amount onto fingertips." },
      { step: "Step 3", title: "Massage for 30-60 Seconds", desc: "Gently massage in circular motions." },
      { step: "Step 4", title: "Rinse & Pat Dry", desc: "Rinse thoroughly and pat dry with a soft towel." }
    ],
    detailedIngredients: [
      { name: "Salicylic Acid", benefit: "Unclogs pores and fights acne-causing bacteria", skinType: "Acne Prone" },
      { name: "Tea Tree Extract", benefit: "Natural antibacterial properties", skinType: "Oily Skin" }
    ],
    beforeAfter: { before: gentleCleanserImg, after: gentleCleanserImg },
    customerReviews: [
      { user: "Amit K.", rating: 5, date: "30 Jan 2026", text: "Cleared my severe acne in just 3 weeks!", helpful: 320 }
    ],
    faqs: [
      { q: "Can Teenagers Use It?", a: "Yes, it is very effective for teenage hormonal acne." },
      { q: "Can I Use It Daily?", a: "Start with once a day, then increase to twice a day if your skin tolerates it well." }
    ],
    routine: [
      { step: "Cleanser", product: "COSKINn Acne Control Cleanser" },
      { step: "Toner", product: "COSKINn Face Mist" },
      { step: "Serum", product: "COSKINn Niacinamide Serum" },
      { step: "Moisturiser", product: "COSKINn Daily Moisturiser" },
      { step: "Sunscreen", product: "COSKINn Sunscreen SPF 50" }
    ],
    texture: "Gel",
    netQuantity: "150 ml",
    shelfLife: "24 Months",
    countryOfOrigin: "India",
    manufacturedBy: "COSKINn Labs"
  }
];
