import sunscreenImg from '../assets/images/sunscreen_spf50.webp';
import bodySunscreenImg from '../assets/images/body_sunscreen.webp';
import tintedSunscreenImg from '../assets/images/tinted_sunscreen.webp';
import gentleCleanserImg from '../assets/images/gentle_cleanser.webp';
import cleansingBalmImg from '../assets/images/cleansing_balm.webp';
import lipBalmImg from '../assets/images/lip_balm.webp';
import handCreamImg from '../assets/images/hand_cream.webp';
import pocketPerfumeImg from '../assets/images/pocket_perfume.webp';
import faceMistImg from '../assets/images/face_mist.webp';
import overnightMaskImg from '../assets/images/overnight_mask.webp';
import underEyePatchesImg from '../assets/images/under_eye_patches.webp';
import dailyMoisturiserImg from '../assets/images/daily_moisturiser.webp';
import settingSprayImg from '../assets/images/setting_spray.webp';
import niacinamideSerumImg from '../assets/images/niacinamide_serum.webp';
import giftGlowEssentialsImg from '../assets/images/gift_glow_essentials.webp';
import giftHydrationImg from '../assets/images/gift_hydration.webp';
import giftSunProtectionImg from '../assets/images/gift_sun_protection.webp';
import giftEverydayImg from '../assets/images/gift_everyday.webp';
import giftLuxuryImg from '../assets/images/gift_luxury.webp';
import giftTravelImg from '../assets/images/gift_travel.webp';
import giftGlowRepairImg from '../assets/images/gift_glow_repair.webp';
import giftPremiumImg from '../assets/images/gift_premium.webp';

// Generic gallery images for demo purposes (Side, Back, Lifestyle)
// In a real app, these would be specific to each product.
const getGallery = (mainImg) => [
  mainImg, 
  mainImg.replace('.webp', '_side.webp'),
  mainImg.replace('.webp', '_back.webp'),
  mainImg.replace('.webp', '_lifestyle.webp')
];

export const skincareProducts = [
  { 
    id: 101, 
    name: "COSKINn Sunscreen SPF 50", 
    originalPrice: 899,
    price: 789, 
    discountBadge: "12% OFF",
    rating: 4.8, 
    reviews: 356,
    category: "Skincare", 
    image: sunscreenImg, 
    images: getGallery(sunscreenImg),
    badge: "BEST SELLER",
    shortDescription: "Broad-spectrum SPF 50 protection with a lightweight, non-greasy finish.",
    longDescription: "Our flagship sunscreen provides ultimate UVA and UVB protection while keeping your skin hydrated and glowing. The lightweight formula absorbs instantly without leaving a white cast, making it perfect for daily use under makeup.",
    benefits: ["Broad-spectrum protection", "No white cast", "Hydrating formula", "Non-comedogenic"],
    keyIngredients: ["Zinc Oxide", "Niacinamide", "Hyaluronic Acid"],
    howToUse: "Apply generously to face and neck 15 minutes before sun exposure. Reapply every 2 hours.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Sun Protection, Anti-aging",
    texture: "Lightweight Lotion",
    fragrance: "Fragrance-Free",
    netQuantity: "50ml",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 124
  },
  { 
    id: 102, 
    name: "COSKINn Body Sunscreen SPF 50", 
    originalPrice: 1299,
    price: 1099, 
    discountBadge: "15% OFF",
    rating: 4.7, 
    reviews: 218,
    category: "Skincare", 
    image: bodySunscreenImg, 
    images: getGallery(bodySunscreenImg),
    badge: "NEW",
    shortDescription: "Full-body sun protection that nourishes and shields your skin.",
    longDescription: "A luxurious body sunscreen designed to protect and deeply moisturize your skin. Its fast-absorbing formula ensures you stay protected from harmful rays while enjoying a silky-smooth finish.",
    benefits: ["Water-resistant", "Deeply moisturizing", "Fast-absorbing", "Non-sticky"],
    keyIngredients: ["Titanium Dioxide", "Shea Butter", "Vitamin E"],
    howToUse: "Apply generously all over the body. Massage until fully absorbed.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Sun Protection, Dryness",
    texture: "Cream",
    fragrance: "Subtle Coconut",
    netQuantity: "150ml",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 85
  },
  { 
    id: 103, 
    name: "COSKINn Tinted Sunscreen SPF 50", 
    originalPrice: 999,
    price: 899, 
    discountBadge: "10% OFF",
    rating: 4.9, 
    reviews: 412,
    category: "Skincare", 
    image: tintedSunscreenImg, 
    images: getGallery(tintedSunscreenImg),
    badge: "TRENDING",
    shortDescription: "Sun protection meets sheer, glowing coverage.",
    longDescription: "Combine your daily sun protection with a flawless, sheer tint. This tinted sunscreen evens out skin tone while providing robust SPF 50 defense, leaving a radiant, dewy finish.",
    benefits: ["Evens skin tone", "Radiant finish", "High sun protection", "Blurs imperfections"],
    keyIngredients: ["Iron Oxides", "Zinc Oxide", "Squalane"],
    howToUse: "Apply evenly to the face as the last step of your skincare routine.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Uneven Skin Tone, Sun Protection",
    texture: "Tinted Fluid",
    fragrance: "Fragrance-Free",
    netQuantity: "50ml",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 210
  },
  { 
    id: 104, 
    name: "COSKINn Gentle Cleanser", 
    originalPrice: 599,
    price: 499, 
    discountBadge: "16% OFF",
    rating: 4.8, 
    reviews: 589,
    category: "Skincare", 
    image: gentleCleanserImg, 
    images: getGallery(gentleCleanserImg),
    badge: "MUST HAVE",
    shortDescription: "A hydrating, non-stripping cleanser for daily purification.",
    longDescription: "Gently remove dirt, oil, and makeup without disrupting your skin's natural barrier. Formulated with soothing botanical extracts, this cleanser leaves skin feeling fresh, soft, and balanced.",
    benefits: ["Non-stripping", "Removes makeup", "Soothes skin", "pH balanced"],
    keyIngredients: ["Ceramides", "Aloe Vera", "Chamomile Extract"],
    howToUse: "Massage a small amount onto damp skin in circular motions. Rinse thoroughly.",
    suitableSkinType: "Sensitive & Dry Skin",
    skinConcerns: "Dryness, Redness",
    texture: "Gel-to-Foam",
    fragrance: "Mild Floral",
    netQuantity: "100ml",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 340
  },
  { 
    id: 105, 
    name: "COSKINn Cleansing Balm", 
    originalPrice: 899,
    price: 719, 
    discountBadge: "20% OFF",
    rating: 4.9, 
    reviews: 1024,
    category: "Skincare", 
    image: cleansingBalmImg, 
    images: getGallery(cleansingBalmImg),
    badge: "VIRAL",
    shortDescription: "Melt away stubborn makeup effortlessly with this luxurious balm.",
    longDescription: "Experience the ultimate first cleanse. This buttery cleansing balm transforms into a silky oil upon application, melting away waterproof makeup, sunscreen, and impurities while nourishing the skin.",
    benefits: ["Melts waterproof makeup", "Nourishing", "Leaves zero residue", "Softens skin"],
    keyIngredients: ["Papaya Extract", "Sunflower Seed Oil", "Vitamin E"],
    howToUse: "Scoop a generous amount and massage onto dry skin. Add water to emulsify, then rinse.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Makeup Removal, Clogged Pores",
    texture: "Solid Balm to Oil",
    fragrance: "Subtle Citrus",
    netQuantity: "80g",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 150
  },
  { 
    id: 106, 
    name: "COSKINn Lip Balm SPF", 
    originalPrice: 349,
    price: 299, 
    discountBadge: "14% OFF",
    rating: 4.7, 
    reviews: 420,
    category: "Skincare", 
    image: lipBalmImg, 
    images: getGallery(lipBalmImg),
    badge: "DAILY ESSENTIAL",
    shortDescription: "Hydrating lip care with essential sun protection.",
    longDescription: "Protect your delicate lips from sun damage while keeping them soft and plump. This SPF-infused lip balm delivers intense hydration and a subtle sheen.",
    benefits: ["Sun protection", "Intense hydration", "Heals chapped lips", "Subtle sheen"],
    keyIngredients: ["Shea Butter", "Beeswax", "SPF Filters"],
    howToUse: "Apply generously to lips as needed, especially before sun exposure.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Dry/Chapped Lips, Sun Protection",
    texture: "Smooth Stick",
    fragrance: "Strawberry",
    netQuantity: "4g",
    shelfLife: "18 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 500
  },
  { 
    id: 107, 
    name: "COSKINn Nourishing Hand Cream", 
    originalPrice: 499,
    price: 439, 
    discountBadge: "12% OFF",
    rating: 4.8, 
    reviews: 185,
    category: "Skincare", 
    image: handCreamImg, 
    images: getGallery(handCreamImg),
    badge: "NEW",
    shortDescription: "Silky, fast-absorbing hydration for dry hands.",
    longDescription: "Revive dry, overworked hands with our intensely nourishing hand cream. Its non-greasy formula absorbs quickly, leaving hands feeling velvety soft and beautifully scented.",
    benefits: ["Intense hydration", "Non-greasy", "Softens cuticles", "Long-lasting moisture"],
    keyIngredients: ["Shea Butter", "Almond Oil", "Glycerin"],
    howToUse: "Massage into hands and cuticles whenever they feel dry.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Dryness, Rough Texture",
    texture: "Rich Cream",
    fragrance: "Rose & Vanilla",
    netQuantity: "50g",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 220
  },
  { 
    id: 108, 
    name: "COSKINn Pocket Perfume", 
    originalPrice: 399,
    price: 349, 
    discountBadge: "12% OFF",
    rating: 4.6, 
    reviews: 310,
    category: "Skincare", 
    image: pocketPerfumeImg, 
    images: getGallery(pocketPerfumeImg),
    badge: "ON-THE-GO",
    shortDescription: "A luxurious, long-lasting fragrance in a travel-friendly size.",
    longDescription: "Carry luxury wherever you go. Our pocket perfume features a highly concentrated blend of floral and musky notes, designed to keep you feeling fresh and elegant all day.",
    benefits: ["Travel-friendly", "Long-lasting", "Premium scent", "Elegant packaging"],
    keyIngredients: ["Essential Oils", "Perfume Base"],
    howToUse: "Spray on pulse points (wrists, neck, behind ears) as desired.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Body Odor, Fragrance",
    texture: "Liquid Spray",
    fragrance: "Floral Musk",
    netQuantity: "20ml",
    shelfLife: "36 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 180
  },
  { 
    id: 109, 
    name: "COSKINn Face Mist", 
    originalPrice: 599,
    price: 499, 
    discountBadge: "16% OFF",
    rating: 4.8, 
    reviews: 275,
    category: "Skincare", 
    image: faceMistImg, 
    images: getGallery(faceMistImg),
    badge: "REFRESHING",
    shortDescription: "An instant boost of hydration and glow.",
    longDescription: "Revitalize tired skin with a single spritz. Infused with rose water and hyaluronic acid, this face mist instantly hydrates, soothes, and sets makeup for a dewy finish.",
    benefits: ["Instant hydration", "Sets makeup", "Soothes skin", "Dewy finish"],
    keyIngredients: ["Rose Water", "Hyaluronic Acid", "Green Tea Extract"],
    howToUse: "Hold 8-10 inches away from face and spray evenly. Use throughout the day to refresh.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Dehydration, Dullness",
    texture: "Fine Mist",
    fragrance: "Fresh Rose",
    netQuantity: "100ml",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 290
  },
  { 
    id: 110, 
    name: "COSKINn Overnight Mask", 
    originalPrice: 1299,
    price: 1099, 
    discountBadge: "15% OFF",
    rating: 4.9, 
    reviews: 512,
    category: "Skincare", 
    image: overnightMaskImg, 
    images: getGallery(overnightMaskImg),
    badge: "AWARD WINNER",
    shortDescription: "Wake up to plumper, more radiant skin.",
    longDescription: "Work with your skin's natural nightly repair process. This luxurious overnight mask intensely hydrates, repairs the moisture barrier, and visibly brightens your complexion by morning.",
    benefits: ["Deep repair", "Intense hydration", "Brightens skin", "Plumping effect"],
    keyIngredients: ["Peptides", "Ceramides", "Vitamin C"],
    howToUse: "Apply a generous layer as the final step of your evening routine. Leave on overnight.",
    suitableSkinType: "Dry & Combination Skin",
    skinConcerns: "Dullness, Fine Lines, Dryness",
    texture: "Gel-Cream",
    fragrance: "Lavender Dream",
    netQuantity: "50g",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 115
  },
  { 
    id: 111, 
    name: "COSKINn Under Eye Patches", 
    originalPrice: 799,
    price: 679, 
    discountBadge: "15% OFF",
    rating: 4.7, 
    reviews: 388,
    category: "Skincare", 
    image: underEyePatchesImg, 
    images: getGallery(underEyePatchesImg),
    badge: "LUXURY",
    shortDescription: "Instant depuffing and brightening for tired eyes.",
    longDescription: "Revitalize your under-eye area in 15 minutes. These cooling hydrogel patches are infused with caffeine and collagen to visibly reduce dark circles, puffiness, and fine lines.",
    benefits: ["Depuffs", "Reduces dark circles", "Smooths fine lines", "Cooling effect"],
    keyIngredients: ["Caffeine", "Collagen", "Gold Extract"],
    howToUse: "Apply onto clean, dry under-eye area. Leave on for 15-20 minutes, then discard.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Dark Circles, Puffiness",
    texture: "Hydrogel",
    fragrance: "Fragrance-Free",
    netQuantity: "30 Pairs",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 160
  },
  { 
    id: 112, 
    name: "COSKINn Daily Moisturiser", 
    originalPrice: 899,
    price: 799, 
    discountBadge: "11% OFF",
    rating: 4.8, 
    reviews: 640,
    category: "Skincare", 
    image: dailyMoisturiserImg, 
    images: getGallery(dailyMoisturiserImg),
    badge: "ESSENTIAL",
    shortDescription: "24-hour hydration with a lightweight feel.",
    longDescription: "Lock in moisture all day long with our daily moisturiser. The perfectly balanced formula absorbs quickly, leaving skin supple, smooth, and prepped for makeup.",
    benefits: ["24-hour hydration", "Lightweight", "Improves skin texture", "Non-greasy"],
    keyIngredients: ["Hyaluronic Acid", "Squalane", "Vitamin E"],
    howToUse: "Apply morning and night to cleansed face and neck.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Dryness, Uneven Texture",
    texture: "Lightweight Cream",
    fragrance: "Mild Fresh",
    netQuantity: "50ml",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 450
  },
  { 
    id: 113, 
    name: "COSKINn Hydrating Setting Spray", 
    originalPrice: 699,
    price: 579, 
    discountBadge: "17% OFF",
    rating: 4.7, 
    reviews: 215,
    category: "Skincare", 
    image: settingSprayImg, 
    images: getGallery(settingSprayImg),
    badge: "NEW",
    shortDescription: "Lock in your look with a burst of hydration.",
    longDescription: "A micro-fine setting spray that fuses makeup and skincare. It sets makeup for up to 16 hours while delivering a continuous boost of hydration, ensuring a radiant, non-cakey finish.",
    benefits: ["16-hour wear", "Hydrating", "Micro-fine mist", "Radiant finish"],
    keyIngredients: ["Aloe Vera", "Green Tea Extract", "Glycerin"],
    howToUse: "Shake well. Hold 8-10 inches away and spray in an 'X' and 'T' motion.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Makeup Longevity, Dryness",
    texture: "Fine Liquid Mist",
    fragrance: "Fresh Aloe",
    netQuantity: "100ml",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 280
  },
  { 
    id: 114, 
    name: "COSKINn Niacinamide Serum", 
    originalPrice: 1099,
    price: 879, 
    discountBadge: "20% OFF",
    rating: 4.9, 
    reviews: 890,
    category: "Skincare", 
    image: niacinamideSerumImg, 
    images: getGallery(niacinamideSerumImg),
    badge: "HOLY GRAIL",
    shortDescription: "Potent 10% Niacinamide to refine pores and tone.",
    longDescription: "Transform your skin texture with our potent Niacinamide serum. Formulated to minimize the appearance of enlarged pores, control excess sebum, and fade dark spots for a clear, luminous complexion.",
    benefits: ["Minimizes pores", "Controls oil", "Fades dark spots", "Improves skin tone"],
    keyIngredients: ["10% Niacinamide", "Zinc PCA", "Hyaluronic Acid"],
    howToUse: "Apply 2-3 drops to clean skin before heavier creams, morning and night.",
    suitableSkinType: "Oily, Combination, & Acne-Prone Skin",
    skinConcerns: "Enlarged Pores, Blemishes, Oiliness",
    texture: "Lightweight Serum",
    fragrance: "Fragrance-Free",
    netQuantity: "30ml",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 195
  },
  { 
    id: 201, 
    name: "COSKINn Glow Essentials Gift Set", 
    originalPrice: 2597,
    price: 1999, 
    discountBadge: "23% OFF",
    rating: 4.9, 
    reviews: 512,
    category: "Gift Sets", 
    image: giftGlowEssentialsImg, 
    images: getGallery(giftGlowEssentialsImg),
    badge: "PERFECT GIFT",
    shortDescription: "A curated trio featuring Niacinamide Serum, Gentle Cleanser, and Daily Moisturiser.",
    longDescription: "Give the gift of radiant skin. This beautifully packaged Glow Essentials Gift Set includes everything needed for a complete, brightening daily routine. Housed in a premium COSKINn luxury box with a beautiful ribbon finish.",
    benefits: ["Complete daily routine", "Brightens complexion", "Luxury gift packaging", "Exceptional value"],
    keyIngredients: ["Niacinamide", "Ceramides", "Hyaluronic Acid"],
    howToUse: "Step 1: Cleanse. Step 2: Apply Serum. Step 3: Lock in with Moisturiser.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Dullness, Uneven Texture",
    texture: "Various",
    fragrance: "Signature Fresh",
    netQuantity: "3 Items",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 150
  },
  { 
    id: 202, 
    name: "COSKINn Hydration Ritual Gift Set", 
    originalPrice: 2597,
    price: 1899, 
    discountBadge: "26% OFF",
    rating: 4.8, 
    reviews: 320,
    category: "Gift Sets", 
    image: giftHydrationImg, 
    images: getGallery(giftHydrationImg),
    badge: "BEST SELLER",
    shortDescription: "The ultimate hydration boost featuring Face Mist, Moisturiser, and Overnight Mask.",
    longDescription: "Quench thirsty skin with this ultimate hydration bundle. Packed inside a premium gift box, this set ensures 72-hour moisture and a dewy, glowing complexion for any special occasion.",
    benefits: ["72-hour hydration", "Repairs skin barrier", "Premium presentation box", "Plumps skin"],
    keyIngredients: ["Hyaluronic Acid", "Rose Water", "Peptides"],
    howToUse: "Mist throughout the day, moisturise morning and night, and use the mask overnight.",
    suitableSkinType: "Dry & Combination Skin",
    skinConcerns: "Dehydration, Dullness",
    texture: "Various",
    fragrance: "Rose & Lavender",
    netQuantity: "3 Items",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 85
  },
  { 
    id: 203, 
    name: "COSKINn Sun Protection Kit", 
    originalPrice: 2547,
    price: 1799, 
    discountBadge: "29% OFF",
    rating: 4.7, 
    reviews: 410,
    category: "Gift Sets", 
    image: giftSunProtectionImg, 
    images: getGallery(giftSunProtectionImg),
    badge: "TRAVEL ESSENTIAL",
    shortDescription: "Complete SPF defense with Face Sunscreen, Body Sunscreen, and SPF Lip Balm.",
    longDescription: "The perfect getaway gift. This beautifully wrapped kit provides comprehensive broad-spectrum SPF 50 protection from head to toe. Keep their skin safe, hydrated, and protected.",
    benefits: ["Full body protection", "No white cast", "Travel ready", "Premium gift packaging"],
    keyIngredients: ["Zinc Oxide", "Titanium Dioxide", "Shea Butter"],
    howToUse: "Apply generously to face, body, and lips 15 minutes before sun exposure.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Sun Protection, Anti-aging",
    texture: "Lotions & Balm",
    fragrance: "Subtle Coconut",
    netQuantity: "3 Items",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 200
  },
  { 
    id: 204, 
    name: "COSKINn Everyday Essentials Kit", 
    originalPrice: 1997,
    price: 1499, 
    discountBadge: "25% OFF",
    rating: 4.8, 
    reviews: 625,
    category: "Gift Sets", 
    image: giftEverydayImg, 
    images: getGallery(giftEverydayImg),
    badge: "PERFECT GIFT",
    shortDescription: "The daily must-haves: Gentle Cleanser, Moisturiser, and Hand Cream.",
    longDescription: "A universally loved gift. This kit features our most popular daily essentials designed to keep skin clean, soft, and deeply moisturised. Elegantly boxed for any celebration.",
    benefits: ["Gentle care", "Deeply moisturizing", "Great for beginners", "Luxury packaging"],
    keyIngredients: ["Ceramides", "Aloe Vera", "Almond Oil"],
    howToUse: "Cleanse face daily, apply moisturiser, and use hand cream as needed.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Dryness, Maintenance",
    texture: "Various",
    fragrance: "Mild Floral",
    netQuantity: "3 Items",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 310
  },
  { 
    id: 205, 
    name: "COSKINn Luxury Self-Care Box", 
    originalPrice: 3596,
    price: 2699, 
    discountBadge: "25% OFF",
    rating: 4.9, 
    reviews: 185,
    category: "Gift Sets", 
    image: giftLuxuryImg, 
    images: getGallery(giftLuxuryImg),
    badge: "LIMITED EDITION",
    shortDescription: "The ultimate indulgence: Cleansing Balm, Face Mist, Eye Patches, and Overnight Mask.",
    longDescription: "Treat someone special to the ultimate spa-at-home experience. This deluxe box includes our viral cleansing balm, refreshing face mist, luxurious gold eye patches, and repair mask.",
    benefits: ["Spa-at-home", "Deep repair", "Luxury unboxing experience", "Premium ingredients"],
    keyIngredients: ["Gold Extract", "Papaya Extract", "Peptides"],
    howToUse: "Melt makeup with balm, mist face, apply eye patches, and finish with overnight mask.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Stress, Fatigue, Dullness",
    texture: "Various",
    fragrance: "Calming Spa",
    netQuantity: "4 Items",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 50
  },
  { 
    id: 206, 
    name: "COSKINn Travel Skincare Kit", 
    originalPrice: 1899,
    price: 1399, 
    discountBadge: "26% OFF",
    rating: 4.7, 
    reviews: 440,
    category: "Gift Sets", 
    image: giftTravelImg, 
    images: getGallery(giftTravelImg),
    badge: "TRAVEL READY",
    shortDescription: "Mini Cleanser, Mini Moisturiser, Mini Sunscreen, and full-size Lip Balm.",
    longDescription: "Never compromise on skincare while traveling. This TSA-friendly kit comes in a beautiful bespoke travel pouch inside a premium gift box, containing all the essentials for glowing skin on the go.",
    benefits: ["TSA-friendly sizes", "Complete routine", "Includes travel pouch", "Perfect for vacations"],
    keyIngredients: ["Niacinamide", "Ceramides", "Hyaluronic Acid"],
    howToUse: "Use as a complete 3-step routine while traveling.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Travel, Maintenance",
    texture: "Various",
    fragrance: "Signature Fresh",
    netQuantity: "4 Items",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 180
  },
  { 
    id: 207, 
    name: "COSKINn Glow & Repair Kit", 
    originalPrice: 2997,
    price: 2199, 
    discountBadge: "26% OFF",
    rating: 4.9, 
    reviews: 290,
    category: "Gift Sets", 
    image: giftGlowRepairImg, 
    images: getGallery(giftGlowRepairImg),
    badge: "AWARD WINNER",
    shortDescription: "Powerful repair trio: Niacinamide Serum, Overnight Mask, and Face Mist.",
    longDescription: "The ultimate overnight transformation kit. These three powerful products work synergistically to repair the skin barrier, minimize pores, and deliver intense glowing hydration by morning.",
    benefits: ["Intense repair", "Minimizes pores", "Overnight transformation", "Premium presentation"],
    keyIngredients: ["10% Niacinamide", "Peptides", "Rose Water"],
    howToUse: "Mist skin, apply serum, and lock in with the overnight mask before bed.",
    suitableSkinType: "Oily & Combination Skin",
    skinConcerns: "Pores, Uneven Texture, Barrier Repair",
    texture: "Various",
    fragrance: "Fresh Lavender",
    netQuantity: "3 Items",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 95
  },
  { 
    id: 208, 
    name: "COSKINn Premium Beauty Box", 
    originalPrice: 4795,
    price: 3499, 
    discountBadge: "27% OFF",
    rating: 5.0, 
    reviews: 112,
    category: "Gift Sets", 
    image: giftPremiumImg, 
    images: getGallery(giftPremiumImg),
    badge: "ULTIMATE LUXURY",
    shortDescription: "The complete collection: Cleanser, Serum, Moisturiser, Sunscreen, and Eye Patches.",
    longDescription: "Our most luxurious offering. The Premium Beauty Box contains five of our most celebrated, award-winning formulas housed in a stunning, heavyweight keepsake gift box. The ultimate gift for a true skincare aficionado.",
    benefits: ["Complete luxury routine", "Exceptional value", "Keepsake gift box", "Award-winning formulas"],
    keyIngredients: ["Gold Extract", "10% Niacinamide", "Hyaluronic Acid"],
    howToUse: "Follow the enclosed COSKINn routine guide for optimal results.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Comprehensive Care",
    texture: "Various",
    fragrance: "Signature Fresh",
    netQuantity: "5 Items",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 25
  }
];
