import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { hrApi } from '../../core/api/hr';
import { Receipt, Download, IndianRupee, Loader2, Building2 } from 'lucide-react';
import { format } from 'date-fns';

export const PayrollScreen = () => {
  const [selectedMonth, setSelectedMonth] = useState(format(new Date(), 'yyyy-MM'));
  
  const { data: summary, isLoading: isSummaryLoading } = useQuery({
    queryKey: ['hr', 'payroll-summary'],
    queryFn: () => hrApi.getPayrollSummary()
  });

  const { data: employees, isLoading: isEmpsLoading } = useQuery({
    queryKey: ['hr', 'employees'],
    queryFn: () => hrApi.getEmployees()
  });

  const generateSlip = (emp: any) => {
    // In a real app, this would generate a PDF or fetch it from the backend.
    // For this UI, we mock a download action.
    const slipData = `PAYROLL SLIP - ${format(new Date(selectedMonth + '-01'), 'MMMM yyyy')}
----------------------------------------
Employee: ${emp.name} (${emp.employeeId})
Role: ${emp.role} | Department: ${emp.department}

Earnings:
Basic Salary: ₹${(emp.salary * 0.4).toLocaleString()}
HRA: ₹${(emp.salary * 0.2).toLocaleString()}
Special Allowance: ₹${(emp.salary * 0.4).toLocaleString()}

Total Gross: ₹${emp.salary.toLocaleString()}
----------------------------------------
(Mock PDF generated by HR Panel)`;

    const blob = new Blob([slipData], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `salary_slip_${emp.name.replace(/\s+/g, '_')}_${selectedMonth}.txt`;
    a.click();
  };

  return (
    <div className="max-w-6xl mx-auto space-y-6">
      <div className="flex justify-between items-end">
        <div>
          <h1 className="text-2xl font-bold text-slate-900">Payroll Processing</h1>
          <p className="text-slate-500 text-sm mt-1">Review department budgets and generate employee salary slips.</p>
        </div>
        <input 
          type="month" 
          value={selectedMonth}
          onChange={(e) => setSelectedMonth(e.target.value)}
          className="border-slate-300 rounded-lg p-2 focus:ring-2 focus:ring-indigo-500"
        />
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* Department Summary */}
        <div className="lg:col-span-1 space-y-4">
          <h2 className="text-lg font-bold text-slate-800">Department Summary</h2>
          {isSummaryLoading ? (
            <div className="p-6 text-center text-slate-500 bg-white rounded-2xl border border-slate-200">
              <Loader2 className="h-6 w-6 animate-spin mx-auto mb-2 text-slate-300" />
              Loading...
            </div>
          ) : (
            summary?.map((dept: any) => (
              <div key={dept.department} className="bg-white border border-slate-200 rounded-xl p-5 shadow-sm">
                <div className="flex items-center mb-3">
                  <div className="h-8 w-8 bg-indigo-50 text-indigo-600 rounded-md flex items-center justify-center mr-3">
                    <Building2 className="h-4 w-4" />
                  </div>
                  <h3 className="font-bold text-slate-900">{dept.department}</h3>
                </div>
                <div className="flex justify-between text-sm mb-1">
                  <span className="text-slate-500">Headcount</span>
                  <span className="font-medium">{dept.headcount}</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-slate-500">Total Monthly CTC</span>
                  <span className="font-bold text-slate-900">₹{dept.totalCTC.toLocaleString()}</span>
                </div>
              </div>
            ))
          )}
        </div>

        {/* Employee Slips */}
        <div className="lg:col-span-2">
          <div className="bg-white rounded-2xl shadow-sm border border-slate-200 overflow-hidden">
            <div className="px-6 py-4 border-b border-slate-200 bg-slate-50 flex justify-between items-center">
              <h2 className="font-bold text-slate-800">Salary Slips</h2>
              <span className="text-xs font-medium text-slate-500 px-2 py-1 bg-white border border-slate-200 rounded">
                For: {format(new Date(selectedMonth + '-01'), 'MMMM yyyy')}
              </span>
            </div>
            
            {isEmpsLoading ? (
              <div className="p-12 text-center text-slate-500 flex flex-col items-center">
                <Loader2 className="h-8 w-8 animate-spin text-slate-300 mb-2" />
                Loading employees...
              </div>
            ) : !employees || employees.length === 0 ? (
              <div className="p-12 text-center text-slate-500">
                No employees to process payroll for.
              </div>
            ) : (
              <table className="w-full text-left">
                <thead className="bg-white border-b border-slate-100 text-xs font-semibold text-slate-500 uppercase">
                  <tr>
                    <th className="py-3 px-6">Employee</th>
                    <th className="py-3 px-6">Department</th>
                    <th className="py-3 px-6 text-right">Monthly Gross</th>
                    <th className="py-3 px-6 text-right">Action</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {employees.filter((e: any) => e.status !== 'Terminated').map((emp: any) => (
                    <tr key={emp.id} className="hover:bg-slate-50/50 transition-colors">
                      <td className="py-3 px-6">
                        <div className="font-medium text-slate-900 text-sm">{emp.name}</div>
                        <div className="text-xs text-slate-500 font-mono">{emp.employeeId}</div>
                      </td>
                      <td className="py-3 px-6 text-sm text-slate-600">
                        {emp.department}
                      </td>
                      <td className="py-3 px-6 text-right">
                        <div className="text-sm font-bold text-slate-900">₹{emp.salary.toLocaleString()}</div>
                      </td>
                      <td className="py-3 px-6 text-right">
                        <button 
                          onClick={() => generateSlip(emp)}
                          className="inline-flex items-center px-3 py-1.5 text-xs font-medium text-indigo-700 bg-indigo-50 border border-indigo-200 rounded-lg hover:bg-indigo-100 transition-colors"
                        >
                          <Download className="h-3 w-3 mr-1.5" />
                          Slip
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </div>
        </div>

      </div>
    </div>
  );
};
