import fs from 'fs';
const sunscreenImg = '/assets/' + '../assets/images/sunscreen_spf50.webp'.split('/').pop();
const bodySunscreenImg = '/assets/' + '../assets/images/body_sunscreen.webp'.split('/').pop();
const tintedSunscreenImg = '/assets/' + '../assets/images/tinted_sunscreen.webp'.split('/').pop();
const gentleCleanserImg = '/assets/' + '../assets/images/gentle_cleanser.webp'.split('/').pop();
const cleansingBalmImg = '/assets/' + '../assets/images/cleansing_balm.webp'.split('/').pop();
const lipBalmImg = '/assets/' + '../assets/images/lip_balm.webp'.split('/').pop();
const handCreamImg = '/assets/' + '../assets/images/hand_cream.webp'.split('/').pop();
const pocketPerfumeImg = '/assets/' + '../assets/images/pocket_perfume.webp'.split('/').pop();
const faceMistImg = '/assets/' + '../assets/images/face_mist.webp'.split('/').pop();
const overnightMaskImg = '/assets/' + '../assets/images/overnight_mask.webp'.split('/').pop();
const underEyePatchesImg = '/assets/' + '../assets/images/under_eye_patches.webp'.split('/').pop();
const dailyMoisturiserImg = '/assets/' + '../assets/images/daily_moisturiser.webp'.split('/').pop();
const settingSprayImg = '/assets/' + '../assets/images/setting_spray.webp'.split('/').pop();
const niacinamideSerumImg = '/assets/' + '../assets/images/niacinamide_serum.webp'.split('/').pop();
const giftGlowEssentialsImg = '/assets/' + '../assets/images/gift_glow_essentials.webp'.split('/').pop();
const giftHydrationImg = '/assets/' + '../assets/images/gift_hydration.webp'.split('/').pop();
const giftSunProtectionImg = '/assets/' + '../assets/images/gift_sun_protection.webp'.split('/').pop();
const giftEverydayImg = '/assets/' + '../assets/images/gift_everyday.webp'.split('/').pop();
const giftLuxuryImg = '/assets/' + '../assets/images/gift_luxury.webp'.split('/').pop();
const giftTravelImg = '/assets/' + '../assets/images/gift_travel.webp'.split('/').pop();
const giftGlowRepairImg = '/assets/' + '../assets/images/gift_glow_repair.webp'.split('/').pop();
const giftPremiumImg = '/assets/' + '../assets/images/gift_premium.webp'.split('/').pop();

// Generic gallery images for demo purposes (Side, Back, Lifestyle)
// In a real app, these would be specific to each product.
const getGallery = (mainImg) => [
  mainImg, 
  mainImg.replace('.webp', '_side.webp'),
  mainImg.replace('.webp', '_back.webp'),
  mainImg.replace('.webp', '_lifestyle.webp')
];

const skincareProducts = [
  { 
    id: 101, 
    name: "COSKINn Sunscreen SPF 50", 
    originalPrice: 899,
    price: 789, 
    discountBadge: "12% OFF",
    rating: 4.8, 
    reviews: 356,
    category: "Skincare", 
    image: sunscreenImg, 
    images: getGallery(sunscreenImg),
    badge: "BEST SELLER",
    shortDescription: "Broad-spectrum SPF 50 protection with a lightweight, non-greasy finish.",
    longDescription: "Our flagship sunscreen provides ultimate UVA and UVB protection while keeping your skin hydrated and glowing. The lightweight formula absorbs instantly without leaving a white cast, making it perfect for daily use under makeup.",
    benefits: ["Broad-spectrum protection", "No white cast", "Hydrating formula", "Non-comedogenic"],
    keyIngredients: ["Zinc Oxide", "Niacinamide", "Hyaluronic Acid"],
    howToUse: "Apply generously to face and neck 15 minutes before sun exposure. Reapply every 2 hours.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Sun Protection, Anti-aging",
    texture: "Lightweight Lotion",
    fragrance: "Fragrance-Free",
    netQuantity: "50ml",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 124
  },
  { 
    id: 102, 
    name: "COSKINn Body Sunscreen SPF 50", 
    originalPrice: 1299,
    price: 1099, 
    discountBadge: "15% OFF",
    rating: 4.7, 
    reviews: 218,
    category: "Skincare", 
    image: bodySunscreenImg, 
    images: getGallery(bodySunscreenImg),
    badge: "NEW",
    shortDescription: "Full-body sun protection that nourishes and shields your skin.",
    longDescription: "A luxurious body sunscreen designed to protect and deeply moisturize your skin. Its fast-absorbing formula ensures you stay protected from harmful rays while enjoying a silky-smooth finish.",
    benefits: ["Water-resistant", "Deeply moisturizing", "Fast-absorbing", "Non-sticky"],
    keyIngredients: ["Titanium Dioxide", "Shea Butter", "Vitamin E"],
    howToUse: "Apply generously all over the body. Massage until fully absorbed.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Sun Protection, Dryness",
    texture: "Cream",
    fragrance: "Subtle Coconut",
    netQuantity: "150ml",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 85
  },
  { 
    id: 103, 
    name: "COSKINn Tinted Sunscreen SPF 50", 
    originalPrice: 999,
    price: 899, 
    discountBadge: "10% OFF",
    rating: 4.9, 
    reviews: 412,
    category: "Skincare", 
    image: tintedSunscreenImg, 
    images: getGallery(tintedSunscreenImg),
    badge: "TRENDING",
    shortDescription: "Sun protection meets sheer, glowing coverage.",
    longDescription: "Combine your daily sun protection with a flawless, sheer tint. This tinted sunscreen evens out skin tone while providing robust SPF 50 defense, leaving a radiant, dewy finish.",
    benefits: ["Evens skin tone", "Radiant finish", "High sun protection", "Blurs imperfections"],
    keyIngredients: ["Iron Oxides", "Zinc Oxide", "Squalane"],
    howToUse: "Apply evenly to the face as the last step of your skincare routine.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Uneven Skin Tone, Sun Protection",
    texture: "Tinted Fluid",
    fragrance: "Fragrance-Free",
    netQuantity: "50ml",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 210
  },
  { 
    id: 1031, 
    name: "COSKINn Matte Sunscreen SPF 50", 
    originalPrice: 899,
    price: 749, 
    discountBadge: "16% OFF",
    rating: 4.8, 
    reviews: 310,
    category: "Skincare", 
    image: sunscreenImg, 
    images: getGallery(sunscreenImg),
    badge: "OILY SKIN",
    shortDescription: "Ultra-matte finish sunscreen with oil control.",
    longDescription: "Formulated specifically for oily and combination skin, this SPF 50 sunscreen provides broad-spectrum protection while controlling excess sebum. It leaves a velvety, ultra-matte finish that lasts all day without feeling heavy or clogging pores.",
    benefits: ["Matte finish", "Oil control", "No white cast", "Non-comedogenic"],
    keyIngredients: ["Zinc Oxide", "Silica", "Niacinamide"],
    howToUse: "Apply generously to face and neck 15 minutes before sun exposure.",
    suitableSkinType: "Oily & Combination Skin",
    skinConcerns: "Sun Protection, Oiliness",
    texture: "Lightweight Gel-Cream",
    fragrance: "Fragrance-Free",
    netQuantity: "50ml",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 150
  },
  { 
    id: 1032, 
    name: "COSKINn Dewy Sunscreen SPF 50", 
    originalPrice: 949,
    price: 849, 
    discountBadge: "10% OFF",
    rating: 4.9, 
    reviews: 522,
    category: "Skincare", 
    image: sunscreenImg, 
    images: getGallery(sunscreenImg),
    badge: "DRY SKIN",
    shortDescription: "Intensely hydrating sunscreen for a luminous glow.",
    longDescription: "Perfect for dry and dehydrated skin, this dewy sunscreen locks in moisture while shielding your skin from harmful UV rays. Infused with Hyaluronic Acid and Ceramides, it leaves a beautiful, radiant glow that looks perfect under makeup.",
    benefits: ["Dewy finish", "Intense hydration", "Broad-spectrum", "Radiant glow"],
    keyIngredients: ["Hyaluronic Acid", "Ceramides", "Vitamin E"],
    howToUse: "Apply generously as the final step of your morning skincare routine.",
    suitableSkinType: "Dry & Normal Skin",
    skinConcerns: "Sun Protection, Dryness",
    texture: "Rich Lotion",
    fragrance: "Fragrance-Free",
    netQuantity: "50ml",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 200
  },
  { 
    id: 1033, 
    name: "COSKINn Mineral Sunscreen SPF 30", 
    originalPrice: 799,
    price: 699, 
    discountBadge: "12% OFF",
    rating: 4.7, 
    reviews: 145,
    category: "Skincare", 
    image: sunscreenImg, 
    images: getGallery(sunscreenImg),
    badge: "SENSITIVE SKIN",
    shortDescription: "100% mineral protection for sensitive skin.",
    longDescription: "A gentle, 100% physical sunscreen formulated for sensitive and reactive skin types. With soothing Centella Asiatica and pure Zinc Oxide, it provides reliable SPF 30 protection without causing irritation or breakouts.",
    benefits: ["100% Mineral", "Soothes irritation", "Reef-safe", "Gentle formula"],
    keyIngredients: ["Zinc Oxide", "Centella Asiatica", "Oat Extract"],
    howToUse: "Apply evenly to face and neck. Warm between fingers before applying for easiest blending.",
    suitableSkinType: "Sensitive Skin",
    skinConcerns: "Sun Protection, Redness",
    texture: "Mineral Cream",
    fragrance: "Fragrance-Free",
    netQuantity: "50ml",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 80
  },
  { 
    id: 1034, 
    name: "COSKINn Water Resistant Sunscreen SPF 50", 
    originalPrice: 999,
    price: 899, 
    discountBadge: "10% OFF",
    rating: 4.8, 
    reviews: 275,
    category: "Skincare", 
    image: sunscreenImg, 
    images: getGallery(sunscreenImg),
    badge: "SPORT",
    shortDescription: "High-performance protection for outdoor activities.",
    longDescription: "Designed for active lifestyles, this high-performance sunscreen offers 80 minutes of water and sweat resistance. Its durable formula stays put through swimming and heavy sweating, ensuring you stay protected during all your outdoor adventures.",
    benefits: ["Water Resistant", "Sweat Resistant", "High SPF", "Durable protection"],
    keyIngredients: ["Zinc Oxide", "Titanium Dioxide", "Aloe Vera"],
    howToUse: "Apply generously 15 minutes before sun exposure. Reapply after 80 minutes of swimming or sweating.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Sun Protection, Outdoor Activities",
    texture: "Resistant Lotion",
    fragrance: "Subtle Coconut",
    netQuantity: "80ml",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 110
  },
  { 
    id: 1035, 
    name: "COSKINn Invisible Sunscreen Primer SPF 50", 
    originalPrice: 1099,
    price: 949, 
    discountBadge: "13% OFF",
    rating: 4.9, 
    reviews: 412,
    category: "Skincare", 
    image: sunscreenImg, 
    images: getGallery(sunscreenImg),
    badge: "UNDER MAKEUP",
    shortDescription: "Clear sunscreen that doubles as a makeup primer.",
    longDescription: "A totally clear, weightless sunscreen that perfectly preps skin for makeup. The velvety silicone-based formula blurs pores, grips makeup, and provides invisible SPF 50 protection across all skin tones with absolutely zero white cast.",
    benefits: ["Invisible finish", "Makeup gripping", "Blurs pores", "Weightless"],
    keyIngredients: ["Chemical Filters", "Meadowfoam Seed", "Squalane"],
    howToUse: "Apply as the last step of skincare and before makeup application.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Sun Protection, Makeup Prep",
    texture: "Clear Gel",
    fragrance: "Fragrance-Free",
    netQuantity: "40ml",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 250
  },
  { 
    id: 1036, 
    name: "COSKINn Sunscreen Stick SPF 50", 
    originalPrice: 899,
    price: 799, 
    discountBadge: "11% OFF",
    rating: 4.8, 
    reviews: 320,
    category: "Skincare", 
    image: sunscreenImg, 
    images: getGallery(sunscreenImg),
    badge: "EASY REAPPLY",
    shortDescription: "Convenient stick format for on-the-go reapplication.",
    longDescription: "Reapplying sunscreen has never been easier. This portable, mess-free sunscreen stick glides on smoothly without disturbing makeup. The invisible formula leaves a semi-matte finish, making it perfect for quick touch-ups throughout the day.",
    benefits: ["Easy reapplication", "Travel friendly", "Invisible finish", "Mess-free"],
    keyIngredients: ["Chemical Filters", "Sunflower Seed Oil", "Vitamin E"],
    howToUse: "Glide directly over face and neck. Can be used over makeup for reapplication.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Sun Protection, Reapplication",
    texture: "Solid Stick",
    fragrance: "Fragrance-Free",
    netQuantity: "20g",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 180
  },
  { 
    id: 104, 
    name: "COSKINn Gentle Cleanser", 
    originalPrice: 599,
    price: 499, 
    discountBadge: "16% OFF",
    rating: 4.8, 
    reviews: 589,
    category: "Skincare", 
    image: gentleCleanserImg, 
    images: getGallery(gentleCleanserImg),
    badge: "MUST HAVE",
    shortDescription: "A hydrating, non-stripping cleanser for daily purification.",
    longDescription: "Gently remove dirt, oil, and makeup without disrupting your skin's natural barrier. Formulated with soothing botanical extracts, this cleanser leaves skin feeling fresh, soft, and balanced.",
    benefits: ["Non-stripping", "Removes makeup", "Soothes skin", "pH balanced"],
    keyIngredients: ["Ceramides", "Aloe Vera", "Chamomile Extract"],
    howToUse: "Massage a small amount onto damp skin in circular motions. Rinse thoroughly.",
    suitableSkinType: "Sensitive & Dry Skin",
    skinConcerns: "Dryness, Redness",
    texture: "Gel-to-Foam",
    fragrance: "Mild Floral",
    netQuantity: "100ml",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 340
  },
  { 
    id: 105, 
    name: "COSKINn Cleansing Balm", 
    originalPrice: 899,
    price: 719, 
    discountBadge: "20% OFF",
    rating: 4.9, 
    reviews: 1024,
    category: "Skincare", 
    image: cleansingBalmImg, 
    images: getGallery(cleansingBalmImg),
    badge: "VIRAL",
    shortDescription: "Melt away stubborn makeup effortlessly with this luxurious balm.",
    longDescription: "Experience the ultimate first cleanse. This buttery cleansing balm transforms into a silky oil upon application, melting away waterproof makeup, sunscreen, and impurities while nourishing the skin.",
    benefits: ["Melts waterproof makeup", "Nourishing", "Leaves zero residue", "Softens skin"],
    keyIngredients: ["Papaya Extract", "Sunflower Seed Oil", "Vitamin E"],
    howToUse: "Scoop a generous amount and massage onto dry skin. Add water to emulsify, then rinse.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Makeup Removal, Clogged Pores",
    texture: "Solid Balm to Oil",
    fragrance: "Subtle Citrus",
    netQuantity: "80g",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 150
  },
  { 
    id: 1051, 
    name: "COSKINn Cleansing Balm Mini", 
    originalPrice: 399,
    price: 299, 
    discountBadge: "25% OFF",
    rating: 4.8, 
    reviews: 312,
    category: "Skincare", 
    image: cleansingBalmImg, 
    images: getGallery(cleansingBalmImg),
    badge: "TRAVEL SIZE",
    shortDescription: "Perfect travel companion to melt away makeup on-the-go.",
    longDescription: "All the power of our signature cleansing balm in a travel-friendly mini size. Melting texture that leaves skin perfectly prepped for secondary cleansing.",
    benefits: ["Travel-friendly", "Nourishing", "Melts waterproof mascara", "Non-stripping"],
    keyIngredients: ["Papaya Extract", "Sunflower Seed Oil", "Vitamin E"],
    howToUse: "Scoop a hazelnut-sized amount and massage onto dry skin. Rinse with warm water.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Makeup Removal, Impurities",
    texture: "Solid Balm to Oil",
    fragrance: "Subtle Citrus",
    netQuantity: "25g",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 120
  },
  { 
    id: 1052, 
    name: "COSKINn Cleansing Balm Jumbo Pack", 
    originalPrice: 1499,
    price: 1199, 
    discountBadge: "20% OFF",
    rating: 4.9, 
    reviews: 567,
    category: "Skincare", 
    image: cleansingBalmImg, 
    images: getGallery(cleansingBalmImg),
    badge: "BEST VALUE",
    shortDescription: "Our signature makeup-melting balm in a jumbo eco-friendly size.",
    longDescription: "Get more of what you love. Our double-sized jumbo pack ensures you never run out of your favorite first cleanse, while reducing packaging waste by 30%.",
    benefits: ["Value size", "Eco-friendly packaging", "Deep cleansing", "Skin hydrating"],
    keyIngredients: ["Papaya Extract", "Sunflower Seed Oil", "Vitamin E"],
    howToUse: "Scoop a generous amount and massage onto dry skin. Emulsify and rinse off.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Makeup Removal, Clogged Pores",
    texture: "Solid Balm to Oil",
    fragrance: "Subtle Citrus",
    netQuantity: "150g",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 80
  },
  { 
    id: 1053, 
    name: "COSKINn Rose Infused Cleansing Balm", 
    originalPrice: 999,
    price: 799, 
    discountBadge: "20% OFF",
    rating: 4.8, 
    reviews: 145,
    category: "Skincare", 
    image: cleansingBalmImg, 
    images: getGallery(cleansingBalmImg),
    badge: "NEW LAUNCH",
    shortDescription: "Infused with pure rose damascena wax for a soothing floral cleanse.",
    longDescription: "A luxurious floral variant of our bestselling balm. Nourishes dry and sensitive skin while calming irritation and melting away stubborn foundation and mascara.",
    benefits: ["Soothing floral scent", "Calms redness", "Extra nourishing", "Non-irritating"],
    keyIngredients: ["Rose Damascena Wax", "Rosehip Oil", "Sweet Almond Oil"],
    howToUse: "Warm between palms and massage gently onto dry face. Emulsify and wipe clean.",
    suitableSkinType: "Dry & Sensitive Skin",
    skinConcerns: "Redness, Dryness, Makeup Removal",
    texture: "Buttery Rose Balm",
    fragrance: "Natural Damask Rose",
    netQuantity: "80g",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 65
  },
  { 
    id: 1054, 
    name: "COSKINn Charcoal Pore Cleansing Balm", 
    originalPrice: 949,
    price: 749, 
    discountBadge: "21% OFF",
    rating: 4.7, 
    reviews: 98,
    category: "Skincare", 
    image: cleansingBalmImg, 
    images: getGallery(cleansingBalmImg),
    badge: "PORE CLEARING",
    shortDescription: "Activated charcoal draws out impurities and excess sebum.",
    longDescription: "Perfect for oily and acne-prone skin. Infused with black activated charcoal to clarify pores, prevent blackheads, and dissolve oily sebum alongside makeup.",
    benefits: ["Detoxifies skin", "Reduces blackheads", "Balances oil production", "Deep pore clean"],
    keyIngredients: ["Activated Bamboo Charcoal", "Salicylic Acid", "Tea Tree Oil"],
    howToUse: "Massage over face, paying extra attention to T-zone. Emulsify and rinse thoroughly.",
    suitableSkinType: "Oily & Acne-Prone Skin",
    skinConcerns: "Excess Sebum, Blackheads, Pores",
    texture: "Clarifying Black Balm",
    fragrance: "Eucalyptus & Tea Tree",
    netQuantity: "80g",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 45
  },
  { 
    id: 1055, 
    name: "COSKINn Matcha Soothing Cleansing Balm", 
    originalPrice: 969,
    price: 769, 
    discountBadge: "20% OFF",
    rating: 4.8, 
    reviews: 112,
    category: "Skincare", 
    image: cleansingBalmImg, 
    images: getGallery(cleansingBalmImg),
    badge: "CALMING",
    shortDescription: "Antioxidant-rich organic matcha green tea calms stressed skin.",
    longDescription: "Enriched with ceremonial grade matcha green tea extract to neutralize environmental pollutants while lifting away face and eye makeup without stripping skin moisture.",
    benefits: ["Antioxidant-rich", "Neutralizes pollutants", "Calms skin irritation", "Non-drying"],
    keyIngredients: ["Organic Matcha Powder", "Green Tea Seed Oil", "Centella Asiatica"],
    howToUse: "Apply to dry face, massage, add warm water to turn into milk, and rinse off.",
    suitableSkinType: "Sensitive & Combination Skin",
    skinConcerns: "Irritation, Pollution Defense",
    texture: "Green Creamy Balm",
    fragrance: "Calming Green Tea",
    netQuantity: "80g",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 50
  },
  { 
    id: 1056, 
    name: "COSKINn Cleansing Balm Double Duo", 
    originalPrice: 1798,
    price: 1299, 
    discountBadge: "27% OFF",
    rating: 4.9, 
    reviews: 489,
    category: "Skincare", 
    image: cleansingBalmImg, 
    images: getGallery(cleansingBalmImg),
    badge: "COMBO DEAL",
    shortDescription: "Double the glow. A set of two full-sized cleansing balms.",
    longDescription: "Keep one on your vanity and one in your travel kit. Contains two full-sized jars of our bestselling makeup-melting balm to guarantee continuous clear skin.",
    benefits: ["Bundle savings", "Stock up value", "Perfect first cleanse duo", "Deeply nourishing"],
    keyIngredients: ["Papaya Extract", "Sunflower Seed Oil", "Vitamin E"],
    howToUse: "Use a scoop daily as the first step of your double cleansing routine.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Makeup Removal, Impurities",
    texture: "Solid Balm to Oil",
    fragrance: "Subtle Citrus",
    netQuantity: "2 x 80g",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 110
  },
  { 
    id: 1057, 
    name: "COSKINn Cleansing Balm & Mist Set", 
    originalPrice: 1398,
    price: 1049, 
    discountBadge: "25% OFF",
    rating: 4.9, 
    reviews: 224,
    category: "Skincare", 
    image: cleansingBalmImg, 
    images: getGallery(cleansingBalmImg),
    badge: "BEST SELLER",
    shortDescription: "A complete skin prep duo: Cleansing Balm and Face Mist.",
    longDescription: "Melt away makeup with our nourishing Cleansing Balm, then follow up with our Strawberry Glow Face Mist to lock in hydration and antioxidants.",
    benefits: ["Complete prep routine", "Hydrates & refreshes", "Melts makeup easily", "Dermatologist choice"],
    keyIngredients: ["Papaya Extract", "Strawberry Extract", "Vitamin E", "Hyaluronic Acid"],
    howToUse: "First cleanse with balm, rinse, then mist face generously to lock in moisture.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Makeup Removal, Dehydration",
    texture: "Balm + Mist Set",
    fragrance: "Citrus & Strawberry",
    netQuantity: "80g + 100ml",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 75
  },
  { 
    id: 106, 
    name: "COSKINn Lip Balm SPF", 
    originalPrice: 349,
    price: 299, 
    discountBadge: "14% OFF",
    rating: 4.7, 
    reviews: 420,
    category: "Skincare", 
    image: lipBalmImg, 
    images: getGallery(lipBalmImg),
    badge: "DAILY ESSENTIAL",
    shortDescription: "Hydrating lip care with essential sun protection.",
    longDescription: "Protect your delicate lips from sun damage while keeping them soft and plump. This SPF-infused lip balm delivers intense hydration and a subtle sheen.",
    benefits: ["Sun protection", "Intense hydration", "Heals chapped lips", "Subtle sheen"],
    keyIngredients: ["Shea Butter", "Beeswax", "SPF Filters"],
    howToUse: "Apply generously to lips as needed, especially before sun exposure.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Dry/Chapped Lips, Sun Protection",
    texture: "Smooth Stick",
    fragrance: "Strawberry",
    netQuantity: "4g",
    shelfLife: "18 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 500
  },
  { 
    id: 107, 
    name: "COSKINn Nourishing Hand Cream", 
    originalPrice: 499,
    price: 439, 
    discountBadge: "12% OFF",
    rating: 4.8, 
    reviews: 185,
    category: "Skincare", 
    image: handCreamImg, 
    images: getGallery(handCreamImg),
    badge: "NEW",
    shortDescription: "Silky, fast-absorbing hydration for dry hands.",
    longDescription: "Revive dry, overworked hands with our intensely nourishing hand cream. Its non-greasy formula absorbs quickly, leaving hands feeling velvety soft and beautifully scented.",
    benefits: ["Intense hydration", "Non-greasy", "Softens cuticles", "Long-lasting moisture"],
    keyIngredients: ["Shea Butter", "Almond Oil", "Glycerin"],
    howToUse: "Massage into hands and cuticles whenever they feel dry.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Dryness, Rough Texture",
    texture: "Rich Cream",
    fragrance: "Rose & Vanilla",
    netQuantity: "50g",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 220
  },
  { 
    id: 108, 
    name: "COSKINn Pocket Perfume", 
    originalPrice: 399,
    price: 349, 
    discountBadge: "12% OFF",
    rating: 4.6, 
    reviews: 310,
    category: "Skincare", 
    image: pocketPerfumeImg, 
    images: getGallery(pocketPerfumeImg),
    badge: "ON-THE-GO",
    shortDescription: "A luxurious, long-lasting fragrance in a travel-friendly size.",
    longDescription: "Carry luxury wherever you go. Our pocket perfume features a highly concentrated blend of floral and musky notes, designed to keep you feeling fresh and elegant all day.",
    benefits: ["Travel-friendly", "Long-lasting", "Premium scent", "Elegant packaging"],
    keyIngredients: ["Essential Oils", "Perfume Base"],
    howToUse: "Spray on pulse points (wrists, neck, behind ears) as desired.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Body Odor, Fragrance",
    texture: "Liquid Spray",
    fragrance: "Floral Musk",
    netQuantity: "20ml",
    shelfLife: "36 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 180
  },
  { 
    id: 109, 
    name: "COSKINn Face Mist", 
    originalPrice: 599,
    price: 499, 
    discountBadge: "16% OFF",
    rating: 4.8, 
    reviews: 275,
    category: "Skincare", 
    image: faceMistImg, 
    images: getGallery(faceMistImg),
    badge: "REFRESHING",
    shortDescription: "An instant boost of hydration and glow.",
    longDescription: "Revitalize tired skin with a single spritz. Infused with rose water and hyaluronic acid, this face mist instantly hydrates, soothes, and sets makeup for a dewy finish.",
    benefits: ["Instant hydration", "Sets makeup", "Soothes skin", "Dewy finish"],
    keyIngredients: ["Rose Water", "Hyaluronic Acid", "Green Tea Extract"],
    howToUse: "Hold 8-10 inches away from face and spray evenly. Use throughout the day to refresh.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Dehydration, Dullness",
    texture: "Fine Mist",
    fragrance: "Fresh Rose",
    netQuantity: "100ml",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 290
  },
  {
    id: 1091,
    name: "COSKINn Rose Glow Face Mist",
    originalPrice: 699,
    price: 549,
    discountBadge: "21% OFF",
    rating: 4.9,
    reviews: 612,
    category: "Skincare",
    image: faceMistImg,
    images: getGallery(faceMistImg),
    badge: "BEST SELLER",
    shortDescription: "Damask rose water mist for a glow-boosting refresh.",
    longDescription: "Infused with pure Damask rose water and Vitamin C, this luxurious mist instantly brightens dull skin while delivering a surge of antioxidant protection. A staple for glowing skin lovers.",
    benefits: ["Glow Boosting", "Brightening", "Antioxidant rich", "All-day hydration"],
    keyIngredients: ["Damask Rose Water", "Vitamin C", "Hyaluronic Acid"],
    howToUse: "Spritz over clean or made-up skin, holding 8 inches away. Use morning, afternoon, or as a makeup setting spray.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Dullness, Dehydration",
    texture: "Ultra-Fine Mist",
    fragrance: "Fresh Rose",
    netQuantity: "100ml",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 320
  },
  {
    id: 1092,
    name: "COSKINn Aloe Vera Hydra Mist",
    originalPrice: 599,
    price: 479,
    discountBadge: "20% OFF",
    rating: 4.8,
    reviews: 441,
    category: "Skincare",
    image: faceMistImg,
    images: getGallery(faceMistImg),
    badge: "SOOTHING",
    shortDescription: "Pure aloe vera mist to calm and intensely hydrate.",
    longDescription: "Packed with 98% pure aloe vera juice and panthenol, this hydrating mist instantly quenches thirsty skin, soothes irritation, and provides a plumping effect throughout the day.",
    benefits: ["Aloe Vera", "Deep hydration", "Soothes redness", "Instant relief"],
    keyIngredients: ["Aloe Vera Juice", "Panthenol", "Glycerin"],
    howToUse: "Mist over face any time your skin needs a hydration boost. No rinsing needed.",
    suitableSkinType: "Sensitive & Dry Skin",
    skinConcerns: "Dehydration, Redness, Irritation",
    texture: "Water-light Mist",
    fragrance: "Fragrance-Free",
    netQuantity: "100ml",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 280
  },
  {
    id: 1093,
    name: "COSKINn Vitamin C Brightening Mist",
    originalPrice: 749,
    price: 599,
    discountBadge: "20% OFF",
    rating: 4.9,
    reviews: 538,
    category: "Skincare",
    image: faceMistImg,
    images: getGallery(faceMistImg),
    badge: "GLOW BOOSTER",
    shortDescription: "Vitamin C-charged mist for radiant, even-toned skin.",
    longDescription: "A powerhouse brightening mist with stabilized Vitamin C, niacinamide, and ferulic acid. Corrects dullness, fades dark spots, and gives your skin a luminous boost with every spray.",
    benefits: ["Vitamin C", "Brightening", "Dark spot fading", "Even skin tone"],
    keyIngredients: ["Stabilized Vitamin C", "Niacinamide", "Ferulic Acid"],
    howToUse: "Spray 2-3 times over face in the morning for a radiance boost.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Dullness, Pigmentation",
    texture: "Serum Mist",
    fragrance: "Mild Citrus",
    netQuantity: "100ml",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 190
  },
  {
    id: 1094,
    name: "COSKINn Watermelon Glow Mist",
    originalPrice: 649,
    price: 499,
    discountBadge: "23% OFF",
    rating: 4.7,
    reviews: 312,
    category: "Skincare",
    image: faceMistImg,
    images: getGallery(faceMistImg),
    badge: "NEW LAUNCH",
    shortDescription: "Juicy watermelon extract for a dewy, glassy glow.",
    longDescription: "Summertime in a bottle. Loaded with watermelon fruit extract and beta-glucan, this refreshing mist provides a cooling sensation, locks in moisture, and leaves a beautiful dewy glow.",
    benefits: ["Glow Boosting", "Cooling effect", "Dewy finish", "Anti-oxidant"],
    keyIngredients: ["Watermelon Extract", "Beta-Glucan", "Hyaluronic Acid"],
    howToUse: "Use before and after makeup for a dewy-fresh look all day.",
    suitableSkinType: "Normal & Combination Skin",
    skinConcerns: "Dullness, Dehydration",
    texture: "Aqua Mist",
    fragrance: "Fresh Watermelon",
    netQuantity: "100ml",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 145
  },
  {
    id: 1095,
    name: "COSKINn Green Tea Antioxidant Mist",
    originalPrice: 649,
    price: 519,
    discountBadge: "20% OFF",
    rating: 4.8,
    reviews: 265,
    category: "Skincare",
    image: faceMistImg,
    images: getGallery(faceMistImg),
    badge: "ANTIOXIDANT",
    shortDescription: "Green tea-powered antioxidant mist for pollution defense.",
    longDescription: "Your urban shield. Rich in EGCG catechins from ceremonial green tea extract, this antioxidant-packed mist neutralizes free radicals, combats pollution, and keeps skin fresh and balanced all day.",
    benefits: ["Antioxidant shield", "Pollution defense", "Balancing", "Calming"],
    keyIngredients: ["Green Tea Extract", "EGCG", "Zinc PCA"],
    howToUse: "Apply in the morning after moisturizer for all-day pollution defense.",
    suitableSkinType: "Oily & Combination Skin",
    skinConcerns: "Pollution, Oiliness, Dullness",
    texture: "Balancing Mist",
    fragrance: "Matcha Green Tea",
    netQuantity: "100ml",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 210
  },
  {
    id: 1096,
    name: "COSKINn Lavender Sleep Mist",
    originalPrice: 699,
    price: 549,
    discountBadge: "21% OFF",
    rating: 4.9,
    reviews: 398,
    category: "Skincare",
    image: faceMistImg,
    images: getGallery(faceMistImg),
    badge: "NIGHT RITUAL",
    shortDescription: "Calming lavender mist to prep skin for overnight repair.",
    longDescription: "The perfect bedtime ritual. Infused with organic lavender essential oil and ceramides, this restorative night mist calms the mind, soothes skin, and supports the skin's natural overnight recovery process.",
    benefits: ["Calming lavender", "Supports overnight repair", "Ceramide boost", "Stress relief"],
    keyIngredients: ["Lavender Essential Oil", "Ceramides", "Chamomile Extract"],
    howToUse: "Mist generously over face and neck before applying your night cream.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Stress, Dryness, Dullness",
    texture: "Calming Mist",
    fragrance: "Organic Lavender",
    netQuantity: "100ml",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 175
  },
  {
    id: 1097,
    name: "COSKINn Travel Face Mist Mini",
    originalPrice: 399,
    price: 299,
    discountBadge: "25% OFF",
    rating: 4.7,
    reviews: 489,
    category: "Skincare",
    image: faceMistImg,
    images: getGallery(faceMistImg),
    badge: "TRAVEL SIZE",
    shortDescription: "Pocket-size face mist for anytime, anywhere hydration.",
    longDescription: "Don't let your skin dry out on the go. This compact, airline-approved travel mist packs all the hydrating power of our bestselling face mist in a purse-friendly 30ml size.",
    benefits: ["Travel Size", "Airline approved", "Instant refresh", "On-the-go hydration"],
    keyIngredients: ["Rose Water", "Hyaluronic Acid", "Aloe Vera"],
    howToUse: "Carry in your purse and spritz whenever skin needs a refresh.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Dehydration, Travel Dryness",
    texture: "Fine Mist",
    fragrance: "Fresh Rose",
    netQuantity: "30ml",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 420
  },
  { 
    id: 110, 
    name: "COSKINn Overnight Mask", 
    originalPrice: 1299,
    price: 1099, 
    discountBadge: "15% OFF",
    rating: 4.9, 
    reviews: 512,
    category: "Skincare", 
    image: overnightMaskImg, 
    images: getGallery(overnightMaskImg),
    badge: "AWARD WINNER",
    shortDescription: "Wake up to plumper, more radiant skin.",
    longDescription: "Work with your skin's natural nightly repair process. This luxurious overnight mask intensely hydrates, repairs the moisture barrier, and visibly brightens your complexion by morning.",
    benefits: ["Deep repair", "Intense hydration", "Brightens skin", "Plumping effect"],
    keyIngredients: ["Peptides", "Ceramides", "Vitamin C"],
    howToUse: "Apply a generous layer as the final step of your evening routine. Leave on overnight.",
    suitableSkinType: "Dry & Combination Skin",
    skinConcerns: "Dullness, Fine Lines, Dryness",
    texture: "Gel-Cream",
    fragrance: "Lavender Dream",
    netQuantity: "50g",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 115
  },
  { 
    id: 111, 
    name: "COSKINn Under Eye Patches", 
    originalPrice: 799,
    price: 679, 
    discountBadge: "15% OFF",
    rating: 4.7, 
    reviews: 388,
    category: "Skincare", 
    image: underEyePatchesImg, 
    images: getGallery(underEyePatchesImg),
    badge: "LUXURY",
    shortDescription: "Instant depuffing and brightening for tired eyes.",
    longDescription: "Revitalize your under-eye area in 15 minutes. These cooling hydrogel patches are infused with caffeine and collagen to visibly reduce dark circles, puffiness, and fine lines.",
    benefits: ["Depuffs", "Reduces dark circles", "Smooths fine lines", "Cooling effect"],
    keyIngredients: ["Caffeine", "Collagen", "Gold Extract"],
    howToUse: "Apply onto clean, dry under-eye area. Leave on for 15-20 minutes, then discard.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Dark Circles, Puffiness",
    texture: "Hydrogel",
    fragrance: "Fragrance-Free",
    netQuantity: "30 Pairs",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 160
  },
  { 
    id: 112, 
    name: "COSKINn Daily Moisturiser", 
    originalPrice: 899,
    price: 799, 
    discountBadge: "11% OFF",
    rating: 4.8, 
    reviews: 640,
    category: "Skincare", 
    image: dailyMoisturiserImg, 
    images: getGallery(dailyMoisturiserImg),
    badge: "ESSENTIAL",
    shortDescription: "24-hour hydration with a lightweight feel.",
    longDescription: "Lock in moisture all day long with our daily moisturiser. The perfectly balanced formula absorbs quickly, leaving skin supple, smooth, and prepped for makeup.",
    benefits: ["24-hour hydration", "Lightweight", "Improves skin texture", "Non-greasy"],
    keyIngredients: ["Hyaluronic Acid", "Squalane", "Vitamin E"],
    howToUse: "Apply morning and night to cleansed face and neck.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Dryness, Uneven Texture",
    texture: "Lightweight Cream",
    fragrance: "Mild Fresh",
    netQuantity: "50ml",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 450
  },
  { 
    id: 113, 
    name: "COSKINn Hydrating Setting Spray", 
    originalPrice: 699,
    price: 579, 
    discountBadge: "17% OFF",
    rating: 4.7, 
    reviews: 215,
    category: "Skincare", 
    image: settingSprayImg, 
    images: getGallery(settingSprayImg),
    badge: "NEW",
    shortDescription: "Lock in your look with a burst of hydration.",
    longDescription: "A micro-fine setting spray that fuses makeup and skincare. It sets makeup for up to 16 hours while delivering a continuous boost of hydration, ensuring a radiant, non-cakey finish.",
    benefits: ["16-hour wear", "Hydrating", "Micro-fine mist", "Radiant finish"],
    keyIngredients: ["Aloe Vera", "Green Tea Extract", "Glycerin"],
    howToUse: "Shake well. Hold 8-10 inches away and spray in an 'X' and 'T' motion.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Makeup Longevity, Dryness",
    texture: "Fine Liquid Mist",
    fragrance: "Fresh Aloe",
    netQuantity: "100ml",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 280
  },
  { 
    id: 114, 
    name: "COSKINn Niacinamide Serum", 
    originalPrice: 1099,
    price: 879, 
    discountBadge: "20% OFF",
    rating: 4.9, 
    reviews: 890,
    category: "Skincare", 
    image: niacinamideSerumImg, 
    images: getGallery(niacinamideSerumImg),
    badge: "HOLY GRAIL",
    shortDescription: "Potent 10% Niacinamide to refine pores and tone.",
    longDescription: "Transform your skin texture with our potent Niacinamide serum. Formulated to minimize the appearance of enlarged pores, control excess sebum, and fade dark spots for a clear, luminous complexion.",
    benefits: ["Minimizes pores", "Controls oil", "Fades dark spots", "Improves skin tone"],
    keyIngredients: ["10% Niacinamide", "Zinc PCA", "Hyaluronic Acid"],
    howToUse: "Apply 2-3 drops to clean skin before heavier creams, morning and night.",
    suitableSkinType: "Oily, Combination, & Acne-Prone Skin",
    skinConcerns: "Enlarged Pores, Blemishes, Oiliness",
    texture: "Lightweight Serum",
    fragrance: "Fragrance-Free",
    netQuantity: "30ml",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 195
  },
  { 
    id: 201, 
    name: "COSKINn Glow Essentials Gift Set", 
    originalPrice: 2597,
    price: 1999, 
    discountBadge: "23% OFF",
    rating: 4.9, 
    reviews: 512,
    category: "Gift Sets", 
    image: giftGlowEssentialsImg, 
    images: getGallery(giftGlowEssentialsImg),
    badge: "PERFECT GIFT",
    shortDescription: "A curated trio featuring Niacinamide Serum, Gentle Cleanser, and Daily Moisturiser.",
    longDescription: "Give the gift of radiant skin. This beautifully packaged Glow Essentials Gift Set includes everything needed for a complete, brightening daily routine. Housed in a premium COSKINn luxury box with a beautiful ribbon finish.",
    benefits: ["Complete daily routine", "Brightens complexion", "Luxury gift packaging", "Exceptional value"],
    keyIngredients: ["Niacinamide", "Ceramides", "Hyaluronic Acid"],
    howToUse: "Step 1: Cleanse. Step 2: Apply Serum. Step 3: Lock in with Moisturiser.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Dullness, Uneven Texture",
    texture: "Various",
    fragrance: "Signature Fresh",
    netQuantity: "3 Items",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 150
  },
  { 
    id: 202, 
    name: "COSKINn Hydration Ritual Gift Set", 
    originalPrice: 2597,
    price: 1899, 
    discountBadge: "26% OFF",
    rating: 4.8, 
    reviews: 320,
    category: "Gift Sets", 
    image: giftHydrationImg, 
    images: getGallery(giftHydrationImg),
    badge: "BEST SELLER",
    shortDescription: "The ultimate hydration boost featuring Face Mist, Moisturiser, and Overnight Mask.",
    longDescription: "Quench thirsty skin with this ultimate hydration bundle. Packed inside a premium gift box, this set ensures 72-hour moisture and a dewy, glowing complexion for any special occasion.",
    benefits: ["72-hour hydration", "Repairs skin barrier", "Premium presentation box", "Plumps skin"],
    keyIngredients: ["Hyaluronic Acid", "Rose Water", "Peptides"],
    howToUse: "Mist throughout the day, moisturise morning and night, and use the mask overnight.",
    suitableSkinType: "Dry & Combination Skin",
    skinConcerns: "Dehydration, Dullness",
    texture: "Various",
    fragrance: "Rose & Lavender",
    netQuantity: "3 Items",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 85
  },
  { 
    id: 203, 
    name: "COSKINn Sun Protection Kit", 
    originalPrice: 2547,
    price: 1799, 
    discountBadge: "29% OFF",
    rating: 4.7, 
    reviews: 410,
    category: "Gift Sets", 
    image: giftSunProtectionImg, 
    images: getGallery(giftSunProtectionImg),
    badge: "TRAVEL ESSENTIAL",
    shortDescription: "Complete SPF defense with Face Sunscreen, Body Sunscreen, and SPF Lip Balm.",
    longDescription: "The perfect getaway gift. This beautifully wrapped kit provides comprehensive broad-spectrum SPF 50 protection from head to toe. Keep their skin safe, hydrated, and protected.",
    benefits: ["Full body protection", "No white cast", "Travel ready", "Premium gift packaging"],
    keyIngredients: ["Zinc Oxide", "Titanium Dioxide", "Shea Butter"],
    howToUse: "Apply generously to face, body, and lips 15 minutes before sun exposure.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Sun Protection, Anti-aging",
    texture: "Lotions & Balm",
    fragrance: "Subtle Coconut",
    netQuantity: "3 Items",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 200
  },
  { 
    id: 204, 
    name: "COSKINn Everyday Essentials Kit", 
    originalPrice: 1997,
    price: 1499, 
    discountBadge: "25% OFF",
    rating: 4.8, 
    reviews: 625,
    category: "Gift Sets", 
    image: giftEverydayImg, 
    images: getGallery(giftEverydayImg),
    badge: "PERFECT GIFT",
    shortDescription: "The daily must-haves: Gentle Cleanser, Moisturiser, and Hand Cream.",
    longDescription: "A universally loved gift. This kit features our most popular daily essentials designed to keep skin clean, soft, and deeply moisturised. Elegantly boxed for any celebration.",
    benefits: ["Gentle care", "Deeply moisturizing", "Great for beginners", "Luxury packaging"],
    keyIngredients: ["Ceramides", "Aloe Vera", "Almond Oil"],
    howToUse: "Cleanse face daily, apply moisturiser, and use hand cream as needed.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Dryness, Maintenance",
    texture: "Various",
    fragrance: "Mild Floral",
    netQuantity: "3 Items",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 310
  },
  { 
    id: 205, 
    name: "COSKINn Luxury Self-Care Box", 
    originalPrice: 3596,
    price: 2699, 
    discountBadge: "25% OFF",
    rating: 4.9, 
    reviews: 185,
    category: "Gift Sets", 
    image: giftLuxuryImg, 
    images: getGallery(giftLuxuryImg),
    badge: "LIMITED EDITION",
    shortDescription: "The ultimate indulgence: Cleansing Balm, Face Mist, Eye Patches, and Overnight Mask.",
    longDescription: "Treat someone special to the ultimate spa-at-home experience. This deluxe box includes our viral cleansing balm, refreshing face mist, luxurious gold eye patches, and repair mask.",
    benefits: ["Spa-at-home", "Deep repair", "Luxury unboxing experience", "Premium ingredients"],
    keyIngredients: ["Gold Extract", "Papaya Extract", "Peptides"],
    howToUse: "Melt makeup with balm, mist face, apply eye patches, and finish with overnight mask.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Stress, Fatigue, Dullness",
    texture: "Various",
    fragrance: "Calming Spa",
    netQuantity: "4 Items",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 50
  },
  { 
    id: 206, 
    name: "COSKINn Travel Skincare Kit", 
    originalPrice: 1899,
    price: 1399, 
    discountBadge: "26% OFF",
    rating: 4.7, 
    reviews: 440,
    category: "Gift Sets", 
    image: giftTravelImg, 
    images: getGallery(giftTravelImg),
    badge: "TRAVEL READY",
    shortDescription: "Mini Cleanser, Mini Moisturiser, Mini Sunscreen, and full-size Lip Balm.",
    longDescription: "Never compromise on skincare while traveling. This TSA-friendly kit comes in a beautiful bespoke travel pouch inside a premium gift box, containing all the essentials for glowing skin on the go.",
    benefits: ["TSA-friendly sizes", "Complete routine", "Includes travel pouch", "Perfect for vacations"],
    keyIngredients: ["Niacinamide", "Ceramides", "Hyaluronic Acid"],
    howToUse: "Use as a complete 3-step routine while traveling.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Travel, Maintenance",
    texture: "Various",
    fragrance: "Signature Fresh",
    netQuantity: "4 Items",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 180
  },
  { 
    id: 207, 
    name: "COSKINn Glow & Repair Kit", 
    originalPrice: 2997,
    price: 2199, 
    discountBadge: "26% OFF",
    rating: 4.9, 
    reviews: 290,
    category: "Gift Sets", 
    image: giftGlowRepairImg, 
    images: getGallery(giftGlowRepairImg),
    badge: "AWARD WINNER",
    shortDescription: "Powerful repair trio: Niacinamide Serum, Overnight Mask, and Face Mist.",
    longDescription: "The ultimate overnight transformation kit. These three powerful products work synergistically to repair the skin barrier, minimize pores, and deliver intense glowing hydration by morning.",
    benefits: ["Intense repair", "Minimizes pores", "Overnight transformation", "Premium presentation"],
    keyIngredients: ["10% Niacinamide", "Peptides", "Rose Water"],
    howToUse: "Mist skin, apply serum, and lock in with the overnight mask before bed.",
    suitableSkinType: "Oily & Combination Skin",
    skinConcerns: "Pores, Uneven Texture, Barrier Repair",
    texture: "Various",
    fragrance: "Fresh Lavender",
    netQuantity: "3 Items",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 95
  },
  { 
    id: 208, 
    name: "COSKINn Premium Beauty Box", 
    originalPrice: 4795,
    price: 3499, 
    discountBadge: "27% OFF",
    rating: 5.0, 
    reviews: 112,
    category: "Gift Sets", 
    image: giftPremiumImg, 
    images: getGallery(giftPremiumImg),
    badge: "ULTIMATE LUXURY",
    shortDescription: "The complete collection: Cleanser, Serum, Moisturiser, Sunscreen, and Eye Patches.",
    longDescription: "Our most luxurious offering. The Premium Beauty Box contains five of our most celebrated, award-winning formulas housed in a stunning, heavyweight keepsake gift box. The ultimate gift for a true skincare aficionado.",
    benefits: ["Complete luxury routine", "Exceptional value", "Keepsake gift box", "Award-winning formulas"],
    keyIngredients: ["Gold Extract", "10% Niacinamide", "Hyaluronic Acid"],
    howToUse: "Follow the enclosed COSKINn routine guide for optimal results.",
    suitableSkinType: "All Skin Types",
    skinConcerns: "Comprehensive Care",
    texture: "Various",
    fragrance: "Signature Fresh",
    netQuantity: "5 Items",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 25
  },
  // --- NEW CLEANSERS WITH ADVANCED PDP DATA ---
  {
    id: 301,
    name: "COSKINn Hydrating Cleanser",
    originalPrice: 899,
    price: 699,
    discountBadge: "22% OFF",
    rating: 4.9,
    reviews: 1450,
    category: "Face Care",
    subcategory: "Cleanser",
    skinTypes: ["Dry Skin", "Normal Skin", "Sensitive Skin"],
    concerns: ["Dryness", "Dullness"],
    image: gentleCleanserImg,
    images: getGallery(gentleCleanserImg),
    badge: "HYDRATION BOOST",
    shortDescription: "A moisture-rich cleanser that melts away impurities without stripping your skin barrier.",
    longDescription: "Formulated with 3 essential ceramides and hyaluronic acid, this non-foaming hydrating cleanser effectively removes dirt and makeup while reinforcing your skin's natural protective barrier.",
    benefits: ["Deep Cleansing", "Hydration", "Maintains Skin Barrier", "Soap Free", "Paraben Free", "Cruelty Free"],
    keyIngredients: ["Ceramides", "Hyaluronic Acid", "Vitamin B5"],
    howToUse: [
      { step: "Step 1", title: "Wet Face", desc: "Splash face with lukewarm water." },
      { step: "Step 2", title: "Apply COSKINn Cleanser", desc: "Pump a coin-sized amount onto fingertips." },
      { step: "Step 3", title: "Massage for 30-60 Seconds", desc: "Gently massage in circular motions." },
      { step: "Step 4", title: "Rinse & Pat Dry", desc: "Rinse thoroughly and pat dry with a soft towel." }
    ],
    detailedIngredients: [
      { name: "Hyaluronic Acid", benefit: "Retains 1000x its weight in water for plump skin", skinType: "All Skin Types" },
      { name: "Ceramides", benefit: "Restores and maintains the skin's natural barrier", skinType: "Dry, Sensitive" },
      { name: "Vitamin B5", benefit: "Soothes and heals compromised skin", skinType: "Sensitive" }
    ],
    beforeAfter: { before: gentleCleanserImg, after: gentleCleanserImg }, // Reusing images for mock
    customerReviews: [
      { user: "Priya S.", rating: 5, date: "12 June 2026", text: "Completely cured my dry patches! Will never use another cleanser.", helpful: 124 },
      { user: "Aarti M.", rating: 4, date: "05 May 2026", text: "Very gentle, doesn't lather much but leaves skin soft.", helpful: 45 }
    ],
    faqs: [
      { q: "Suitable for Sensitive Skin?", a: "Yes, it is dermatologically tested and fragrance-free." },
      { q: "Can Teenagers Use It?", a: "Absolutely. It's gentle enough for daily teenage use." },
      { q: "Does It Remove Sunscreen?", a: "Yes, it effectively removes daily sunscreen and light makeup." }
    ],
    routine: [
      { step: "Cleanser", product: "COSKINn Hydrating Cleanser" },
      { step: "Toner", product: "COSKINn Face Mist" },
      { step: "Serum", product: "COSKINn Niacinamide Serum" },
      { step: "Moisturiser", product: "COSKINn Daily Moisturiser" },
      { step: "Sunscreen", product: "COSKINn Sunscreen SPF 50" }
    ],
    texture: "Creamy Lotion",
    netQuantity: "150 ml",
    shelfLife: "24 Months",
    countryOfOrigin: "India",
    manufacturedBy: "COSKINn Labs"
  },
  {
    id: 302,
    name: "COSKINn Foaming Cleanser",
    originalPrice: 799,
    price: 649,
    discountBadge: "18% OFF",
    rating: 4.8,
    reviews: 980,
    category: "Face Care",
    subcategory: "Cleanser",
    skinTypes: ["Oily Skin", "Combination Skin"],
    concerns: ["Oil Control", "Large Pores", "Acne"],
    image: gentleCleanserImg,
    images: getGallery(gentleCleanserImg),
    badge: "PORE CLEARING",
    shortDescription: "A refreshing foaming gel that deeply cleanses pores and controls excess oil.",
    longDescription: "This gel-to-foam cleanser deeply purifies without disrupting the skin barrier. Infused with Niacinamide to control sebum and tighten pores.",
    benefits: ["Deep Cleansing", "Oil Control", "Dermatologically Tested", "Paraben Free", "Sulphate Free", "Cruelty Free"],
    keyIngredients: ["Niacinamide", "Salicylic Acid", "Green Tea"],
    howToUse: [
      { step: "Step 1", title: "Wet Face", desc: "Splash face with lukewarm water." },
      { step: "Step 2", title: "Apply COSKINn Cleanser", desc: "Pump a coin-sized amount onto fingertips." },
      { step: "Step 3", title: "Massage for 30-60 Seconds", desc: "Gently massage in circular motions." },
      { step: "Step 4", title: "Rinse & Pat Dry", desc: "Rinse thoroughly and pat dry with a soft towel." }
    ],
    detailedIngredients: [
      { name: "Niacinamide", benefit: "Controls oil production and fades marks", skinType: "Oily, Combination" },
      { name: "Green Tea", benefit: "Antioxidant protection and soothing properties", skinType: "Acne Prone" }
    ],
    beforeAfter: { before: gentleCleanserImg, after: gentleCleanserImg },
    customerReviews: [
      { user: "Karan V.", rating: 5, date: "22 May 2026", text: "Best foaming wash for my oily T-zone.", helpful: 89 }
    ],
    faqs: [
      { q: "Can I Use It Daily?", a: "Yes, use twice a day for best results." },
      { q: "Fragrance Free?", a: "Yes, it contains no artificial fragrances." }
    ],
    routine: [
      { step: "Cleanser", product: "COSKINn Foaming Cleanser" },
      { step: "Toner", product: "COSKINn Face Mist" },
      { step: "Serum", product: "COSKINn Niacinamide Serum" },
      { step: "Moisturiser", product: "COSKINn Daily Moisturiser" },
      { step: "Sunscreen", product: "COSKINn Sunscreen SPF 50" }
    ],
    texture: "Gel to Foam",
    netQuantity: "150 ml",
    shelfLife: "24 Months",
    countryOfOrigin: "India",
    manufacturedBy: "COSKINn Labs"
  },
  {
    id: 303,
    name: "COSKINn Gel Cleanser",
    originalPrice: 849,
    price: 699,
    discountBadge: "17% OFF",
    rating: 4.7,
    reviews: 650,
    category: "Face Care",
    subcategory: "Cleanser",
    skinTypes: ["Normal Skin", "Combination Skin", "Sensitive Skin"],
    concerns: ["Blackheads", "Whiteheads"],
    image: gentleCleanserImg,
    images: getGallery(gentleCleanserImg),
    badge: "EVERYDAY GLOW",
    shortDescription: "A mild, pH-balanced gel cleanser for everyday freshness.",
    longDescription: "Formulated with Aloe Vera and Centella Asiatica, this soothing gel cleanser removes daily grime while keeping skin calm and balanced.",
    benefits: ["Hydration", "Maintains Skin Barrier", "Dermatologically Tested", "Cruelty Free"],
    keyIngredients: ["Aloe Vera", "Centella Asiatica"],
    howToUse: [
      { step: "Step 1", title: "Wet Face", desc: "Splash face with lukewarm water." },
      { step: "Step 2", title: "Apply COSKINn Cleanser", desc: "Pump a coin-sized amount onto fingertips." },
      { step: "Step 3", title: "Massage for 30-60 Seconds", desc: "Gently massage in circular motions." },
      { step: "Step 4", title: "Rinse & Pat Dry", desc: "Rinse thoroughly and pat dry with a soft towel." }
    ],
    detailedIngredients: [
      { name: "Aloe Vera", benefit: "Deeply hydrates and calms redness", skinType: "Sensitive" },
      { name: "Centella Asiatica", benefit: "Heals skin barrier", skinType: "All Skin Types" }
    ],
    beforeAfter: { before: gentleCleanserImg, after: gentleCleanserImg },
    customerReviews: [
      { user: "Neha R.", rating: 4, date: "10 Apr 2026", text: "Very refreshing, lovely texture.", helpful: 30 }
    ],
    faqs: [
      { q: "Does It Remove Makeup?", a: "It removes light makeup, but we recommend a double cleanse for heavy makeup." }
    ],
    routine: [
      { step: "Cleanser", product: "COSKINn Gel Cleanser" },
      { step: "Toner", product: "COSKINn Face Mist" },
      { step: "Serum", product: "COSKINn Niacinamide Serum" },
      { step: "Moisturiser", product: "COSKINn Daily Moisturiser" },
      { step: "Sunscreen", product: "COSKINn Sunscreen SPF 50" }
    ],
    texture: "Clear Gel",
    netQuantity: "150 ml",
    shelfLife: "24 Months",
    countryOfOrigin: "India",
    manufacturedBy: "COSKINn Labs"
  },
  {
    id: 304,
    name: "COSKINn Brightening Cleanser",
    originalPrice: 999,
    price: 849,
    discountBadge: "15% OFF",
    rating: 4.8,
    reviews: 880,
    category: "Face Care",
    subcategory: "Cleanser",
    skinTypes: ["Normal Skin", "Dry Skin", "Oily Skin", "Combination Skin"],
    concerns: ["Pigmentation", "Dullness"],
    image: gentleCleanserImg,
    images: getGallery(gentleCleanserImg),
    badge: "RADIANCE",
    shortDescription: "A Vitamin C infused cleanser to instantly brighten and even out skin tone.",
    longDescription: "Wash away dullness and reveal a luminous complexion with this antioxidant-rich cleanser. Vitamin C works to fade dark spots over time.",
    benefits: ["Brightening", "Deep Cleansing", "Sulphate Free", "Cruelty Free"],
    keyIngredients: ["Vitamin C", "Licorice Extract"],
    howToUse: [
      { step: "Step 1", title: "Wet Face", desc: "Splash face with lukewarm water." },
      { step: "Step 2", title: "Apply COSKINn Cleanser", desc: "Pump a coin-sized amount onto fingertips." },
      { step: "Step 3", title: "Massage for 30-60 Seconds", desc: "Gently massage in circular motions." },
      { step: "Step 4", title: "Rinse & Pat Dry", desc: "Rinse thoroughly and pat dry with a soft towel." }
    ],
    detailedIngredients: [
      { name: "Vitamin C", benefit: "Brightens and evens skin tone", skinType: "All Skin Types" },
      { name: "Licorice Extract", benefit: "Fades pigmentation", skinType: "Dull Skin" }
    ],
    beforeAfter: { before: gentleCleanserImg, after: gentleCleanserImg },
    customerReviews: [
      { user: "Rohan D.", rating: 5, date: "02 Mar 2026", text: "Gives an instant glow right after washing!", helpful: 156 }
    ],
    faqs: [
      { q: "Can I Use It Daily?", a: "Yes, it is gentle enough for daily AM and PM use." }
    ],
    routine: [
      { step: "Cleanser", product: "COSKINn Brightening Cleanser" },
      { step: "Toner", product: "COSKINn Face Mist" },
      { step: "Serum", product: "COSKINn Niacinamide Serum" },
      { step: "Moisturiser", product: "COSKINn Daily Moisturiser" },
      { step: "Sunscreen", product: "COSKINn Sunscreen SPF 50" }
    ],
    texture: "Creamy Gel",
    netQuantity: "150 ml",
    shelfLife: "24 Months",
    countryOfOrigin: "India",
    manufacturedBy: "COSKINn Labs"
  },
  {
    id: 305,
    name: "COSKINn Sensitive Cleanser",
    originalPrice: 899,
    price: 749,
    discountBadge: "16% OFF",
    rating: 4.9,
    reviews: 1200,
    category: "Face Care",
    subcategory: "Cleanser",
    skinTypes: ["Sensitive Skin", "Dry Skin"],
    concerns: ["Sensitive Skin", "Dryness"],
    image: gentleCleanserImg,
    images: getGallery(gentleCleanserImg),
    badge: "CALMING",
    shortDescription: "An ultra-gentle, fragrance-free formula for the most reactive skin types.",
    longDescription: "Formulated without essential oils or harsh surfactants, this cleanser purifies without triggering redness or irritation.",
    benefits: ["Maintains Skin Barrier", "Dermatologically Tested", "Soap Free", "Paraben Free", "Sulphate Free", "Cruelty Free"],
    keyIngredients: ["Colloidal Oatmeal", "Ceramides"],
    howToUse: [
      { step: "Step 1", title: "Wet Face", desc: "Splash face with lukewarm water." },
      { step: "Step 2", title: "Apply COSKINn Cleanser", desc: "Pump a coin-sized amount onto fingertips." },
      { step: "Step 3", title: "Massage for 30-60 Seconds", desc: "Gently massage in circular motions." },
      { step: "Step 4", title: "Rinse & Pat Dry", desc: "Rinse thoroughly and pat dry with a soft towel." }
    ],
    detailedIngredients: [
      { name: "Colloidal Oatmeal", benefit: "Clinically proven to soothe redness and itching", skinType: "Sensitive" },
      { name: "Ceramides", benefit: "Restores the skin barrier", skinType: "Sensitive" }
    ],
    beforeAfter: { before: gentleCleanserImg, after: gentleCleanserImg },
    customerReviews: [
      { user: "Shreya P.", rating: 5, date: "14 Feb 2026", text: "The only cleanser that doesn't make my skin burn.", helpful: 210 }
    ],
    faqs: [
      { q: "Suitable for Sensitive Skin?", a: "Yes, it is formulated specifically for hyper-sensitive skin." },
      { q: "Fragrance Free?", a: "100% fragrance and essential oil free." }
    ],
    routine: [
      { step: "Cleanser", product: "COSKINn Sensitive Cleanser" },
      { step: "Toner", product: "COSKINn Face Mist" },
      { step: "Serum", product: "COSKINn Niacinamide Serum" },
      { step: "Moisturiser", product: "COSKINn Daily Moisturiser" },
      { step: "Sunscreen", product: "COSKINn Sunscreen SPF 50" }
    ],
    texture: "Milky Lotion",
    netQuantity: "150 ml",
    shelfLife: "24 Months",
    countryOfOrigin: "India",
    manufacturedBy: "COSKINn Labs"
  },
  {
    id: 306,
    name: "COSKINn Acne Control Cleanser",
    originalPrice: 949,
    price: 799,
    discountBadge: "15% OFF",
    rating: 4.7,
    reviews: 1800,
    category: "Face Care",
    subcategory: "Cleanser",
    skinTypes: ["Oily Skin", "Acne Prone"],
    concerns: ["Acne", "Large Pores", "Blackheads"],
    image: gentleCleanserImg,
    images: getGallery(gentleCleanserImg),
    badge: "BHA POWER",
    shortDescription: "A 2% Salicylic Acid cleanser to fight breakouts and unclog pores.",
    longDescription: "Target active acne and prevent future breakouts with this BHA-infused cleanser. It gently exfoliates dead skin cells while deep-cleaning pores.",
    benefits: ["Oil Control", "Deep Cleansing", "Dermatologically Tested", "Paraben Free", "Cruelty Free"],
    keyIngredients: ["Salicylic Acid", "Tea Tree Extract"],
    howToUse: [
      { step: "Step 1", title: "Wet Face", desc: "Splash face with lukewarm water." },
      { step: "Step 2", title: "Apply COSKINn Cleanser", desc: "Pump a coin-sized amount onto fingertips." },
      { step: "Step 3", title: "Massage for 30-60 Seconds", desc: "Gently massage in circular motions." },
      { step: "Step 4", title: "Rinse & Pat Dry", desc: "Rinse thoroughly and pat dry with a soft towel." }
    ],
    detailedIngredients: [
      { name: "Salicylic Acid", benefit: "Unclogs pores and fights acne-causing bacteria", skinType: "Acne Prone" },
      { name: "Tea Tree Extract", benefit: "Natural antibacterial properties", skinType: "Oily Skin" }
    ],
    beforeAfter: { before: gentleCleanserImg, after: gentleCleanserImg },
    customerReviews: [
      { user: "Amit K.", rating: 5, date: "30 Jan 2026", text: "Cleared my severe acne in just 3 weeks!", helpful: 320 }
    ],
    faqs: [
      { q: "Can Teenagers Use It?", a: "Yes, it is very effective for teenage hormonal acne." },
      { q: "Can I Use It Daily?", a: "Start with once a day, then increase to twice a day if your skin tolerates it well." }
    ],
    routine: [
      { step: "Cleanser", product: "COSKINn Acne Control Cleanser" },
      { step: "Toner", product: "COSKINn Face Mist" },
      { step: "Serum", product: "COSKINn Niacinamide Serum" },
      { step: "Moisturiser", product: "COSKINn Daily Moisturiser" },
      { step: "Sunscreen", product: "COSKINn Sunscreen SPF 50" }
    ],
    texture: "Gel",
    netQuantity: "150 ml",
    shelfLife: "24 Months",
    countryOfOrigin: "India",
    manufacturedBy: "COSKINn Labs"
  },
  { 
    id: 1101, 
    name: "COSKINn Strawberry Pocket Perfume", 
    originalPrice: 2140,
    price: 1499, 
    discountBadge: "30% OFF",
    rating: 4.9, 
    reviews: 1245,
    category: "Skincare", 
    subcategory: "Pocket Perfume",
    image: pocketPerfumeImg, 
    images: getGallery(pocketPerfumeImg),
    badge: "BEST SELLER",
    shortDescription: "Sweet fruity freshness for a playful luxurious aroma.",
    longDescription: "Our signature Strawberry Pocket Perfume captures the essence of fresh summer strawberries. It leaves a playful, sweet, and luxurious aroma that lingers all day, bringing an instant boost of joy to your everyday routine.",
    benefits: ["Long-lasting fruity fragrance", "Travel friendly", "Premium extracts", "Alcohol balanced"],
    keyIngredients: ["Wild Strawberry Extract", "Red Berry Nectar"],
    howToUse: [
      { title: "Target Pulse Points", desc: "Spray lightly on wrists, neck, and behind ears." },
      { title: "Do Not Rub", desc: "Let the perfume dry naturally to preserve the scent notes." },
      { title: "Refresh", desc: "Reapply throughout the day as desired for an instant boost." }
    ],
    detailedIngredients: [
      { name: "Strawberry Extract", benefit: "Provides a fresh, sweet, and playful aromatic opening.", skinType: "All Skin Types" },
      { name: "Red Berry Nectar", benefit: "Adds long-lasting depth to the fruity profile.", skinType: "All Skin Types" },
      { name: "Hydrating Base", benefit: "Ensures the perfume is safe and non-drying on the skin.", skinType: "Sensitive Skin" }
    ],
    customerReviews: [
      { user: "Jessica T.", date: "2 days ago", rating: 5, text: "This is the most luxurious pocket perfume I've ever owned. The Strawberry scent stays all day. Truly high-end!", helpful: 45 },
      { user: "Amanda L.", date: "1 week ago", rating: 5, text: "So convenient for traveling! It fits perfectly in my smallest clutch and gets so many compliments.", helpful: 32 }
    ],
    suitableSkinType: "All Skin Types",
    skinConcerns: "Fragrance",
    texture: "Fine Mist",
    fragrance: "Sweet Strawberry",
    netQuantity: "20ml",
    shelfLife: "36 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 120
  },
  { 
    id: 1102, 
    name: "COSKINn Orange Pocket Perfume", 
    originalPrice: 2130,
    price: 1599, 
    discountBadge: "25% OFF",
    rating: 4.8, 
    reviews: 950,
    category: "Skincare", 
    subcategory: "Pocket Perfume",
    image: pocketPerfumeImg, 
    images: getGallery(pocketPerfumeImg),
    badge: "FRESH & ZESTY",
    shortDescription: "Fresh citrus energy that adds an instant refreshing opening.",
    longDescription: "Awaken your senses with the Orange Pocket Perfume. A vibrant burst of sweet orange and zesty mandarin that provides an instant refreshing aura, perfect for busy days and energetic mornings.",
    benefits: ["Energizing scent", "Travel friendly", "Premium extracts", "Alcohol balanced"],
    keyIngredients: ["Sweet Orange Extract", "Mandarin Zest"],
    howToUse: [
      { title: "Target Pulse Points", desc: "Spray lightly on wrists, neck, and behind ears." },
      { title: "Do Not Rub", desc: "Let the perfume dry naturally to preserve the scent notes." },
      { title: "Refresh", desc: "Reapply throughout the day as desired for an instant boost." }
    ],
    detailedIngredients: [
      { name: "Sweet Orange Extract", benefit: "Delivers an energetic, uplifting citrus aroma.", skinType: "All Skin Types" },
      { name: "Mandarin Zest", benefit: "Adds a sharp, zesty note that revitalizes the senses.", skinType: "All Skin Types" }
    ],
    customerReviews: [
      { user: "Priya M.", date: "3 days ago", rating: 5, text: "Perfect morning scent! Wakes me up and stays fresh all day.", helpful: 28 },
      { user: "Sarah J.", date: "2 weeks ago", rating: 4, text: "Love the citrus notes, it feels very high end.", helpful: 15 }
    ],
    suitableSkinType: "All Skin Types",
    skinConcerns: "Fragrance",
    texture: "Fine Mist",
    fragrance: "Fresh Orange",
    netQuantity: "20ml",
    shelfLife: "36 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 85
  },
  { 
    id: 1103, 
    name: "COSKINn Mango Pocket Perfume", 
    originalPrice: 2165,
    price: 1299, 
    discountBadge: "40% OFF",
    rating: 4.7, 
    reviews: 642,
    category: "Skincare", 
    subcategory: "Pocket Perfume",
    image: pocketPerfumeImg, 
    images: getGallery(pocketPerfumeImg),
    badge: "WARM & CREAMY",
    shortDescription: "Soft tropical warmth that provides creamy fruity comfort.",
    longDescription: "Escape to a tropical paradise. The Mango Pocket Perfume delivers a soft, warm, and creamy fragrance profile that wraps you in a comforting and luxurious exotic aura.",
    benefits: ["Creamy tropical scent", "Travel friendly", "Premium extracts", "Alcohol balanced"],
    keyIngredients: ["Mango Nectar", "Tropical Fruit Blend"],
    howToUse: [
      { title: "Target Pulse Points", desc: "Spray lightly on wrists, neck, and behind ears." },
      { title: "Do Not Rub", desc: "Let the perfume dry naturally to preserve the scent notes." },
      { title: "Refresh", desc: "Reapply throughout the day as desired for an instant boost." }
    ],
    detailedIngredients: [
      { name: "Mango Nectar", benefit: "Provides a warm, creamy, and exotic base note.", skinType: "All Skin Types" },
      { name: "Tropical Fruit Blend", benefit: "Enhances the fragrance with complex fruity layers.", skinType: "All Skin Types" }
    ],
    customerReviews: [
      { user: "Sophie M.", date: "1 month ago", rating: 5, text: "Obsessed with the Mango fragrance. It's sophisticated and not overpowering. Will buy the whole set.", helpful: 89 }
    ],
    suitableSkinType: "All Skin Types",
    skinConcerns: "Fragrance",
    texture: "Fine Mist",
    fragrance: "Warm Mango",
    netQuantity: "20ml",
    shelfLife: "36 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 200
  },
  { 
    id: 1104, 
    name: "COSKINn Blueberry Pocket Perfume", 
    originalPrice: 2530,
    price: 1899, 
    discountBadge: "25% OFF",
    rating: 4.9, 
    reviews: 875,
    category: "Skincare", 
    subcategory: "Pocket Perfume",
    image: pocketPerfumeImg, 
    images: getGallery(pocketPerfumeImg),
    badge: "LUXURY",
    shortDescription: "Antioxidant freshness that adds smooth long-lasting depth.",
    longDescription: "A sophisticated take on fruity fragrances. Blueberry Pocket Perfume offers a smooth, deep, and subtly crisp scent profile that feels incredibly elegant and modern.",
    benefits: ["Sophisticated depth", "Travel friendly", "Premium extracts", "Alcohol balanced"],
    keyIngredients: ["Blueberry Extract", "Wild Berries"],
    howToUse: [
      { title: "Target Pulse Points", desc: "Spray lightly on wrists, neck, and behind ears." },
      { title: "Do Not Rub", desc: "Let the perfume dry naturally to preserve the scent notes." },
      { title: "Refresh", desc: "Reapply throughout the day as desired for an instant boost." }
    ],
    detailedIngredients: [
      { name: "Blueberry Extract", benefit: "Delivers a deep, rich, and sophisticated berry note.", skinType: "All Skin Types" },
      { name: "Wild Berries", benefit: "Adds a crisp, fresh edge to the fragrance.", skinType: "All Skin Types" }
    ],
    customerReviews: [
      { user: "Emma R.", date: "5 days ago", rating: 5, text: "The deepest and most elegant fruity scent I've ever tried.", helpful: 56 }
    ],
    suitableSkinType: "All Skin Types",
    skinConcerns: "Fragrance",
    texture: "Fine Mist",
    fragrance: "Deep Blueberry",
    netQuantity: "20ml",
    shelfLife: "36 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 50
  },
  { 
    id: 1105, 
    name: "COSKINn Pomegranate Pocket Perfume", 
    originalPrice: 1999,
    price: 1499, 
    discountBadge: "25% OFF",
    rating: 4.8, 
    reviews: 730,
    category: "Skincare", 
    subcategory: "Pocket Perfume",
    image: pocketPerfumeImg, 
    images: getGallery(pocketPerfumeImg),
    badge: "RICH & ELEGANT",
    shortDescription: "Elegant richness that creates a sophisticated fruity heart.",
    longDescription: "Bold, rich, and utterly luxurious. Pomegranate Pocket Perfume is a captivating fragrance that balances tartness with deep, elegant fruity notes for a truly memorable signature scent.",
    benefits: ["Rich elegant scent", "Travel friendly", "Premium extracts", "Alcohol balanced"],
    keyIngredients: ["Pomegranate Seed Extract", "Red Fruit Blend"],
    howToUse: [
      { title: "Target Pulse Points", desc: "Spray lightly on wrists, neck, and behind ears." },
      { title: "Do Not Rub", desc: "Let the perfume dry naturally to preserve the scent notes." },
      { title: "Refresh", desc: "Reapply throughout the day as desired for an instant boost." }
    ],
    detailedIngredients: [
      { name: "Pomegranate Seed Extract", benefit: "Provides a rich, tart, and highly elegant aroma.", skinType: "All Skin Types" },
      { name: "Red Fruit Blend", benefit: "Smooths the tartness with deep, sweet undertones.", skinType: "All Skin Types" }
    ],
    customerReviews: [
      { user: "Nina K.", date: "1 week ago", rating: 5, text: "Very premium. Smells exactly like a high-end designer perfume.", helpful: 41 }
    ],
    suitableSkinType: "All Skin Types",
    skinConcerns: "Fragrance",
    texture: "Fine Mist",
    fragrance: "Rich Pomegranate",
    netQuantity: "20ml",
    shelfLife: "36 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 150
  },
  { 
    id: 1106, 
    name: "COSKINn Green Tea Pocket Perfume", 
    originalPrice: 1899,
    price: 1399, 
    discountBadge: "26% OFF",
    rating: 4.9, 
    reviews: 512,
    category: "Skincare", 
    subcategory: "Pocket Perfume",
    image: pocketPerfumeImg, 
    images: getGallery(pocketPerfumeImg),
    badge: "CLEAN & FRESH",
    shortDescription: "Clean fresh finish that leaves a refreshing calming effect.",
    longDescription: "Minimalist, clean, and incredibly fresh. Green Tea Pocket Perfume offers a serene, spa-like fragrance experience that instantly calms the mind and refreshes your presence.",
    benefits: ["Clean calming scent", "Travel friendly", "Premium extracts", "Alcohol balanced"],
    keyIngredients: ["Green Tea Extract", "White Tea Leaves"],
    howToUse: [
      { title: "Target Pulse Points", desc: "Spray lightly on wrists, neck, and behind ears." },
      { title: "Do Not Rub", desc: "Let the perfume dry naturally to preserve the scent notes." },
      { title: "Refresh", desc: "Reapply throughout the day as desired for an instant boost." }
    ],
    detailedIngredients: [
      { name: "Green Tea Extract", benefit: "Delivers a crisp, clean, and highly refreshing scent.", skinType: "All Skin Types" },
      { name: "White Tea Leaves", benefit: "Adds a delicate, soft background note.", skinType: "All Skin Types" }
    ],
    customerReviews: [
      { user: "Aarohi S.", date: "3 weeks ago", rating: 5, text: "The perfect everyday scent. So clean and fresh, never overwhelming.", helpful: 67 }
    ],
    suitableSkinType: "All Skin Types",
    skinConcerns: "Fragrance",
    texture: "Fine Mist",
    fragrance: "Fresh Green Tea",
    netQuantity: "20ml",
    shelfLife: "36 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 90
  },
  { 
    id: 1107, 
    name: "COSKINn Berry Fusion Pocket Perfume", 
    originalPrice: 2299,
    price: 1699, 
    discountBadge: "26% OFF",
    rating: 4.8, 
    reviews: 430,
    category: "Skincare", 
    subcategory: "Pocket Perfume",
    image: pocketPerfumeImg, 
    images: getGallery(pocketPerfumeImg),
    badge: "EXOTIC",
    shortDescription: "A playful fusion of our finest red and blue berries.",
    longDescription: "For those who can't choose just one. Berry Fusion combines the playful sweetness of strawberry with the sophisticated depth of blueberry for an incredibly complex, luxurious scent.",
    benefits: ["Complex fruity profile", "Travel friendly", "Premium extracts", "Alcohol balanced"],
    keyIngredients: ["Mixed Berry Extracts", "Acai Nectar"],
    howToUse: [
      { title: "Target Pulse Points", desc: "Spray lightly on wrists, neck, and behind ears." },
      { title: "Do Not Rub", desc: "Let the perfume dry naturally to preserve the scent notes." },
      { title: "Refresh", desc: "Reapply throughout the day as desired for an instant boost." }
    ],
    detailedIngredients: [
      { name: "Mixed Berry Extracts", benefit: "A dynamic, layered fruity experience.", skinType: "All Skin Types" },
      { name: "Acai Nectar", benefit: "Adds a touch of exotic sweetness.", skinType: "All Skin Types" }
    ],
    customerReviews: [
      { user: "Ria D.", date: "1 month ago", rating: 4, text: "Very unique scent, the berries blend together beautifully.", helpful: 22 }
    ],
    suitableSkinType: "All Skin Types",
    skinConcerns: "Fragrance",
    texture: "Fine Mist",
    fragrance: "Mixed Berries",
    netQuantity: "20ml",
    shelfLife: "36 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 110
  },
  { 
    id: 1108, 
    name: "COSKINn Tropical Bloom Pocket Perfume", 
    originalPrice: 2499,
    price: 1799, 
    discountBadge: "28% OFF",
    rating: 4.9, 
    reviews: 620,
    category: "Skincare", 
    subcategory: "Pocket Perfume",
    image: pocketPerfumeImg, 
    images: getGallery(pocketPerfumeImg),
    badge: "SUMMER ESSENTIAL",
    shortDescription: "The ultimate tropical vacation in a bottle.",
    longDescription: "Capture the essence of a sun-drenched holiday. Tropical Bloom is a vibrant, joyous fragrance that masterfully blends sweet mango, fresh orange, and subtle passionfruit.",
    benefits: ["Vibrant vacation scent", "Travel friendly", "Premium extracts", "Alcohol balanced"],
    keyIngredients: ["Mango Nectar", "Orange Zest", "Passionfruit"],
    howToUse: [
      { title: "Target Pulse Points", desc: "Spray lightly on wrists, neck, and behind ears." },
      { title: "Do Not Rub", desc: "Let the perfume dry naturally to preserve the scent notes." },
      { title: "Refresh", desc: "Reapply throughout the day as desired for an instant boost." }
    ],
    detailedIngredients: [
      { name: "Mango Nectar", benefit: "Provides a warm, creamy tropical base.", skinType: "All Skin Types" },
      { name: "Orange Zest", benefit: "Adds an energetic citrus sparkle.", skinType: "All Skin Types" },
      { name: "Passionfruit", benefit: "A tart, exotic note that completes the profile.", skinType: "All Skin Types" }
    ],
    customerReviews: [
      { user: "Tara W.", date: "2 weeks ago", rating: 5, text: "I wear this every day. It instantly puts me in a good mood!", helpful: 77 }
    ],
    suitableSkinType: "All Skin Types",
    skinConcerns: "Fragrance",
    texture: "Fine Mist",
    fragrance: "Tropical Fruit Blend",
    netQuantity: "20ml",
    shelfLife: "36 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 140
  },
  {
    id: 8001,
    name: "COSKINn Glow Kit",
    category: "Bundles",
    subcategory: "Kit",
    price: 2449,
    originalPrice: 3499,
    discountBadge: "30% OFF",
    rating: 4.9,
    reviews: 1245,
    image: giftGlowEssentialsImg,
    gallery: getGallery(giftGlowEssentialsImg),
    shortDescription: "Everything your skin needs for a healthy, radiant glow. A complete day-to-night routine.",
    longDescription: "The COSKINn Glow Kit is a curated collection of our best-selling essentials designed to hydrate, protect, and repair your skin around the clock.",
    howToUse: [
      { step: "Step 1", title: "Cleanse", description: "Use the Gentle Cleanser morning and night." },
      { step: "Step 2", title: "Refresh", description: "Spritz the Face Mist for instant hydration." },
      { step: "Step 3", title: "Protect", description: "Apply Lip Balm SPF throughout the day." },
      { step: "Step 4", title: "Repair", description: "Use the Overnight Mask before bed." }
    ],
    benefits: [
      { title: "Complete Routine", description: "4 full-sized essentials." },
      { title: "Deep Hydration", description: "Locks in moisture." },
      { title: "Radiant Skin", description: "Boosts natural glow." }
    ],
    keyIngredients: ["Vitamin C", "Hyaluronic Acid", "Fruit Extracts"],
    detailedIngredients: [
      { name: "Strawberry", benefit: "Brightens skin.", skinType: "All" },
      { name: "Mango", benefit: "Nourishes.", skinType: "All" }
    ],
    customerReviews: [
      { user: "Emma R.", date: "1 week ago", rating: 5, text: "The perfect starter kit! My skin has never looked better.", helpful: 142 }
    ],
    suitableSkinType: "All Skin Types",
    skinConcerns: "Dullness, Dryness",
    texture: "Varied",
    fragrance: "Signature Fruit Blend",
    netQuantity: "4 Full Size Products",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 50
  },
  {
    id: "s-99",
    name: "COSKINn Spot Care Gel",
    category: "Skincare",
    subcategory: "Treatments",
    price: 499,
    originalPrice: 699,
    discountBadge: "28% OFF",
    rating: 4.8,
    reviews: 420,
    image: niacinamideSerumImg,
    gallery: getGallery(niacinamideSerumImg),
    shortDescription: "Targeted overnight spot treatment for acne and blemishes.",
    longDescription: "Our Spot Care Gel is formulated with Green Tea and Salicylic Acid to reduce inflammation, minimize redness, and clear breakouts fast.",
    howToUse: [
      { step: "Step 1", title: "Cleanse", description: "Ensure the skin is clean and dry." },
      { step: "Step 2", title: "Apply", description: "Dab a small amount directly onto the blemish." }
    ],
    benefits: [
      { title: "Fast Acting", description: "Reduces size and redness overnight." },
      { title: "Calming", description: "Soothes irritated skin." }
    ],
    keyIngredients: ["Green Tea Extract", "Salicylic Acid", "Tea Tree"],
    detailedIngredients: [
      { name: "Green Tea", benefit: "Calms inflammation.", skinType: "Acne-prone" }
    ],
    customerReviews: [
      { user: "Sarah L.", date: "2 weeks ago", rating: 5, text: "A lifesaver for breakouts!", helpful: 85 }
    ],
    suitableSkinType: "Acne-prone Skin",
    skinConcerns: "Acne & Blemishes",
    texture: "Clear Gel",
    fragrance: "Unscented",
    netQuantity: "15g",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 100
  },
  {
    id: "s-100",
    name: "COSKINn Barrier Repair Cream",
    category: "Skincare",
    subcategory: "Moisturiser",
    price: 899,
    originalPrice: 1199,
    discountBadge: "25% OFF",
    rating: 4.9,
    reviews: 630,
    image: dailyMoisturiserImg,
    gallery: getGallery(dailyMoisturiserImg),
    shortDescription: "Deeply nourishing cream to heal and protect the skin barrier.",
    longDescription: "Formulated with Ceramides and Blueberry extract, this rich cream repairs compromised skin, locks in moisture, and protects against environmental stressors.",
    howToUse: [
      { step: "Step 1", title: "Apply", description: "Take a coin-sized amount." },
      { step: "Step 2", title: "Massage", description: "Gently massage into face and neck until absorbed." }
    ],
    benefits: [
      { title: "Barrier Repair", description: "Strengthens skin's natural defense." },
      { title: "Deep Moisture", description: "Provides 48H hydration." }
    ],
    keyIngredients: ["Ceramides", "Blueberry Extract", "Panthenol"],
    detailedIngredients: [
      { name: "Ceramides", benefit: "Restores skin barrier.", skinType: "All" }
    ],
    customerReviews: [
      { user: "Jessica W.", date: "1 month ago", rating: 5, text: "Cured my dry, irritated skin in days.", helpful: 112 }
    ],
    suitableSkinType: "Sensitive, Dry, Acne-prone",
    skinConcerns: "Barrier Care, Dry Skin, Acne & Blemishes",
    texture: "Rich Cream",
    fragrance: "Subtle Blueberry",
    netQuantity: "50g",
    shelfLife: "24 Months",
    manufacturedBy: "COSKINn Labs",
    countryOfOrigin: "India",
    stock: 80
  }
];


fs.writeFileSync("catalog.json", JSON.stringify(skincareProducts, null, 2));
console.log("Exported to catalog.json");